### ISSUE TITLE
How to get a window handle for the current view

### ISSUE THREAD

**Issue by Zellear** [canton7/Stylet#100]
as title,thanks

**Comment by Zellear** [comment]
code:
_intPtr = new WindowInteropHelper(Views.RoleSetView).Handle;

**Comment by canton7** [comment]
"How to get window handle for current view as title" doesn't make sense I'm afraid. What are you actually trying to achieve?

**Comment by Zellear** [comment]
how to get the current view ‘s windows handel

发自我的iPhone

在 2020年2月2日，08:29，Antony Male <notifications@github.com> 写道：

﻿

"How to get window handle for current view as title" doesn't make sense I'm afraid. What are you actually trying to achieve?

**Comment by canton7** [comment]
You can get the view from the `View` property on a `Screen`

**Comment by Zellear** [comment]
could you give a example，thans

发自我的iPhone

在 2020年2月3日，00:24，Antony Male <notifications@github.com> 写道：

You can get the view from the View property on a Screen

**Comment by canton7** [comment]
```cs
new WindowInteropHelper((Window)View).Handle;
```

**Comment by Zellear** [comment]
by the way，thank you very much

发自我的iPhone

在 2020年2月3日，07:46，Antony Male <notifications@github.com> 写道：

﻿

new WindowInteropHelper((Window)View).Handle;

**Comment by canton7** [comment]
Closing as (presumably) solved
