### ISSUE TITLE
New to Stylet - stuck on something that should be simple??..

### ISSUE THREAD

**Issue by WillBellJr** [canton7/Stylet#101]
First THANK YOU SO MUCH for your time and effort developing Stylet!
Coming mostly from DevExpress MVVM and a bit of Caliburn, Skylet is just so clean and liberating!

That said, I'm simply trying to implement a ShellWindow with a "TopToolbarView" in a DockPanel, docked at the top.

For testing my bindings, I created in the TopToolbarView a TextBox "TextEntry" and a Button which calls the WindowManager to open a MessageBox that displays the text from the TextBox - simple.

The binding for the TextBox, and button action works great; I type in text, click the button and the entered text is displayed in the MessageBox.

Where I'm stuck, which should be simple(?) is I added a GUARD property for the button which calls !string.IsNullOrEmpty(TextEntry), with the goal being to simply disable the button when there's no text in the TextBox or to enable the button when the first character is typed in.

It's not working??

The Guard property is called ONCE when the app first starts up - and of course the text is Null at that point, and never again?

When I type text, I do get breaks on the SetAndNotify for the TextBox, BUT my CanClickButton guard property is NEVER called again to change the button state from disabled?

What am I missing?  The TopToolbarViewModel is using Conductor<IScreen> as the base.

Or am I wrong in thinking the guard property should also be triggered when the TextEntry property of the ViewModel is changed (INotifyPropertyChanged)?

I feel like I'm missing something so simple and obvious?

Any suggestions or pointers highly appreciated!

**Comment by WillBellJr** [comment]
Ok it WAS simple, and I had meant to look though the docs again BEFORE pen'ing the above message for help.

I had tried various methods, but the answer was found in the Samples.Hello ViewModel:

`        private string _name;
        public string Name
        {
            get { return this._name; }
            set
            {
                SetAndNotify(ref this._name, value);
                **this.NotifyOfPropertyChange(() => this.CanSayHello);**
            }
        }`

Nothing to see here - sorry for wasting your time!

Again, thanks so much for this wonderful framework!

**Comment by canton7** [comment]
Glad you solved it!
