### ISSUE TITLE
<s:ApplicationLoader> required a x:Key attribute then my app do not appear when run Debug

### ISSUE THREAD

**Issue by AncientTree** [canton7/Stylet#102]
My `App.xaml` looked like this:
``` xaml
<Application x:Class="BarberShop.Views.App"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:local="clr-namespace:BarberShop"
             xmlns:s="https://github.com/canton7/Stylet">
    <Application.Resources>
            <s:ApplicationLoader >
                <s:ApplicationLoader.Bootstrapper>
                    <local:MyBootstrapper/>
                </s:ApplicationLoader.Bootstrapper>
            </s:ApplicationLoader>
    </Application.Resources>
</Application>
```
Which is shown in WIKI. it is work well 
until I want to add a custom resource by edit `App.xaml`, it become this:
```xaml
...
<Application.Resources>
        <ResourceDictionary>
            <s:ApplicationLoader >
                <s:ApplicationLoader.Bootstrapper>
                    <local:MyBootstrapper/>
                </s:ApplicationLoader.Bootstrapper>
            </s:ApplicationLoader>

            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="/BarberShop;component/Styles/StyleDictionary.xaml"/>
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </Application.Resources>
...
```
Error asking for a x:Key attribute of `<s:ApplicationLoader>` Tag occur, Therefore I revise it to be `<s:ApplicationLoader x:Key="a">` . Then Error is disappear, but my app window disappear as well😭. As my app window not occur anymore, the Debug Process is run ahead--RAM analysis tool is running.

Here is the console print:
```
单步执行: 正在逐过程执行非用户代码“BarberShop.Views.App.Main”
单步执行: 正在逐过程执行非用户代码“BarberShop.Views.App..ctor”
单步执行: 正在逐过程执行非用户代码“BarberShop.Views.App.InitializeComponent”
```
I can't translate it to EN but may you guys know the meaning .?
ok is about saying _single step running: running codes not created by user “BarberShop.Views.App.Main”_ and so on.

I guess the reson is that Stylet is not aware of the `x:Key="a"` expression. Anyone know how could I fix this? thanks you all!

Hope the nCov 2019 dose not infect by internet from my place😋, good day

**Comment by canton7** [comment]
[See here](https://github.com/canton7/Stylet/wiki/Bootstrapper#adding-resource-dictionaries-to-appxaml)

**Comment by AncientTree** [comment]
> [See here](https://github.com/canton7/Stylet/wiki/Bootstrapper#adding-resource-dictionaries-to-appxaml)

It's really helpful, thank you very much! 

OMG! Do you believe that I have read this page before open this issue and just missed the last paragraph? I blush for that. Thank you again!
