### ISSUE TITLE
Start Application from App.xaml.cs instead of App.xaml

### ISSUE THREAD

**Issue by fengfranklu** [canton7/Stylet#103]
Thanks for the great framework.  Is there a way to start the bootstrapper code from the App.xaml.cs file as opposed to the xaml resources loader.  My previous apps are all started from App.xaml.cs and feels more in control and easy to step through code.  If you could shed some light here. Thank you very much.

**Comment by canton7** [comment]
Sure, you should be able to write the equivalent C#. Something like:

```cs
public App()
{
    Resources = new ApplicationLoader() { Bootstrapper = new Bootstrapper() };
}
```

Or:

```cs
public App()
{
    Resources.MergedDictionaries.Add(new ApplicationLoader() { Bootstrapper = new Bootstrapper() });
}
```

**Comment by fengfranklu** [comment]
Thank you very much it works!!!
