### ISSUE TITLE
Assigning Actions with Setter.Value

### ISSUE THREAD

**Issue by sirdoombox** [canton7/Stylet#106]
I get `'ActionExtension' is not valid for Setter.Value.` on the XAML below even though the property I'm trying to set the value of is valid. Am I doing something wrong or is it a limitation of the system?

```xaml
<mah:DropDownButton Content="Themes"
                    ItemsSource="{Binding Themes}">
    <mah:DropDownButton.ItemContainerStyle>
        <Style BasedOn="{StaticResource {x:Type MenuItem}}" TargetType="{x:Type MenuItem}">
            <Setter Property="Command" Value="{s:Action ChangeTheme}" />
            <Setter Property="CommandParameter" Value="{Binding }" />
        </Style>
    </mah:DropDownButton.ItemContainerStyle>
</mah:DropDownButton>
```

**Comment by canton7** [comment]
I'm afraid it's a WPF limitation: the classes I need to make this work are all internal (`Binding` and friends are special-cased)

**Comment by sirdoombox** [comment]
Alright, shall stick to ICommand for this use-case then, cheers!
