### ISSUE TITLE
Dependency on System.Drawing.Common in .NET Core

### ISSUE THREAD

**Issue by SpoinkyNL** [canton7/Stylet#107]
Hello,

I was wondering why this is required: https://github.com/canton7/Stylet/blob/master/Stylet/Stylet.csproj#L38

I'd rather not have to reference that assembly and have been taking care to avoid it in my code, however since porting from .NET Framework to .NET Core, Stylet seems to require it. And I can't really find any usages outside of the samples.

Could you elaborate on why this is needed? Thanks!

**Comment by canton7** [comment]
Iirc it's for the icons in MessageBoxView/ViewModel.
