### ISSUE TITLE
Trying to understand IChild and how to set the Parent property...

### ISSUE THREAD

**Issue by WillBellJr** [canton7/Stylet#108]
Hi, I have a MainWindowViewModel : Screen,  and a UpperToolbarViewModel : Screen user control area docked at the top of my MainWindowView.

I'm not understanding, from the documentation; it claims that any View derived from an IChild will have its Parent set?

Everything I've tried, short of just manually setting the Parent member to "this" when I construct the UpperToolbarViewModel leaves the Parent member Null?

I saw one of the answers where it was said to use SomeViewModel.ConductWith(this);
when managing multiple active Views within the main window.

Being that I'm passing in the MainWindowViewModel for the **this** parameter, I was sure the Parent member of the Child view would be set, but debugging though the child view constructor shows the Parent member is still null?

Am I supposed to "manually" set the Parent member for each of my Screen based ViewModels, or is the Parent member supposed to automatically get set as per what's mentioned in the documentation?

I'm thinking I shouldn't have to pass a reference to my MainWindowViewModel to all the child ViewModels since its stated that anything that Implements IChild will automatically get the Parent member set?

Any examples, or pointers as to what I may be doing wrong getting the framework to set the Parent of my child ViewModels is appreciated!

Thanks!

**Comment by canton7** [comment]
It's used by conductors, [see here](https://github.com/canton7/Stylet/wiki/Screens-and-Conductors).

**Comment by WillBellJr** [comment]
Hi, thanks for your quick response - I really appreciate you for sharing your wonderful MVVM framework with the community, compared to DevExpress MVVM that I'm coming from, yours is so much easier to use and lightweight!

Yes by now,, I've poured our your wiki documentation for months - especially the Conductors page!

Perhaps I'm just misunderstanding how the Parent property is set or used.  I can appreciate that it's used for lifetime management, activation, etc., I have yet to use that functionality being that so far I'm using persistent Toolbars.

All I was attempting to do was get a reference back to my MainWindowViewModel since that VM exposes services that the UpperToolbar may be interested in using.  (I have broken out a lot of those services now using the IOC w/constructor injection, but it was just a nagging question in my mind as to why the Parent property is Null when I test it in the ToolBar's constructor.

MainWindowViewModel:
`    public MainWindowViewModel(IWindowManager windowManager,IUserEnvironmentInfo userEnvironmentInfo, IApplicationInfo appInformation, IApplicationEventServices appEventServices)
    {

      UserEnvironmentInfo      = userEnvironmentInfo;
      ApplicationEventServices = appEventServices;
      ApplicationInfo          = appInformation;
      WindowManager            = windowManager;

      
      UpperToolbar = new UpperToolbarViewModel(UserEnvironmentInfo,ApplicationEventServices);
      UpperToolbar.ConductWith((IScreenState) this); // Does this set the Parent property??

    }`

UpperToolbarViewModel:
`    public UpperToolbarViewModel(IUserEnvironmentInfo userInfo, IApplicationEventServices appEvents)
    {
      AppEvents = appEvents;
      UserInfo  = userInfo;

      Text = "Hello World!";

      var parent = this.Parent; // <--- this.Parent == null??

    }
`

Previously, I was just passing in as a parameter a reference to the main window VM, but from my understanding of the Docs, I thought the UpperToolbar Parent property would be already set when constructed by the MainWindow view model.

**Comment by canton7** [comment]
> Perhaps I'm just misunderstanding how the Parent property is set or used.

`Parent` is only used when the child wants to be able to request that the parent closes it. [`IChildDelegate`](https://github.com/canton7/Stylet/blob/4fa7b9ca1a45e8d7455b101d7fed5cdc2990d069/Stylet/IConductor.cs#L34), the interface [implemented by objects assigned to the `Parent` property](https://github.com/canton7/Stylet/blob/develop/Stylet/Screen.cs#L304), has a single method which is `CloseItem`.

> All I was attempting to do was get a reference back to my MainWindowViewModel since that VM exposes services that the UpperToolbar may be interested in using. (I have broken out a lot of those services now using the IOC w/constructor injection, but it was just a nagging question in my mind as to why the Parent property is Null when I test it in the ToolBar's constructor.

You're welcome to use the `Parent` property in this way if you wish, but in that case you'll have to set it yourself. The only place where Stylet sets it is when the child is displayed by a conductor.

The ideal situation here is inject those services into the child, so it doesn't have a dependency on its parent.

[`ConductWith`](https://github.com/canton7/Stylet/blob/4fa7b9ca1a45e8d7455b101d7fed5cdc2990d069/Stylet/ScreenExtensions.cs#L123) doesn't set `Parent`. It just activates/deactivates/closes some VM when another VM is activated/deactivated/closed.

**Comment by WillBellJr** [comment]
Thank you for the explanation and advice.

I've consolidated all of my MainWindowViewModel resource properties into a singular interface (IMainWindowViewModelResources - which the MainWindow VM implements), and I pass that interface to my child views; this gives them access to anything they could possibly need (events, window manager etc.,) - eliminating the need for multiple injections into those views.

I can live with this until further learning and/or experience points me down a different path.
