### ISSUE TITLE
Multiple Screen (with Validator set) tabs in a TabControl: ArgumentNullException in ValidatingModelBase.GetErrors()?

### ISSUE THREAD

**Issue by egilhardaeron** [canton7/Stylet#11]
Hello,
first and foremost I would like to thank you for your hard work on this lovely framework: it's lightweight, powerful, with great documentation and basically it's been a lifesaver!

I have been having some issues though while trying to set `Screen` tabs in a `TabControl` with the `Validator` property set (indeed they are needed for CRUD operations in MDI-ish environment). In this situation, the program throws an **`ArgumentNullException`** on **line 273** of **`ValidatingModelBase.cs`**, in the **`GetErrors()`** method.

I figure I'm doing something wrong, I'm fairly new to both WPF and MVVM, but I'm really stumped and can't figure it out. If it's an actual bug, it should be easy to reproduce since I seem to have the same problem when I edit the provided `Stylet.Sample.ModelValidation` sample project like so:

>In **`ShellView.xaml`**

```xaml
<Window ...>
    <Grid>
        <TabControl Style="{StaticResource StyletConductorTabControl}" />
    </Grid>
</Window>
```
>In **`ShellViewModel.cs`**

```csharp
public class ShellViewModel : Conductor<IScreen>.Collection.OneActive {
    public ShellViewModel(UserViewModel userViewModel) {
        this.DisplayName = "Stylet.Samples.ModelValidation";
        this.Items.Add(userViewModel);

        this.ActiveItem = userViewModel;
    }
}
```

**Comment by canton7** [comment]
Let me take a look that, that for getting on touch

**Comment by canton7** [comment]
Yep, it's my bug. I think WPF has changed the way that it calls `INotifyDataErrorInfo.GetErrors()` since I wrote that code. I'll get that fixed up shortly.

**Comment by canton7** [comment]
Sorry, I've been away on vacation for a week. I'm looking at this now.
