### ISSUE TITLE
Problem in WindowManager.ShowWindow when trying to show a view located in another assembly

### ISSUE THREAD

**Issue by puil** [canton7/Stylet#111]
Hello, I want my main assembly to show one view from another assembly. I register the viewModel in the IoC properly and I the instance of the viewModel is created but when I call "this.windowManager.ShowWindow(viewModelInstance)" I get the following error:

"No registrations found for service SaleDocumentsView".

I've been looking at the code for some hours but I can't figure out what's happening. Could anybody help me please?

Thanks

**Comment by canton7** [comment]
Is your `SaleDocumentsView` class in the same assembly as your Bootstrapper?

**Comment by puil** [comment]
Hello, sorry for the late answer. I fixed it the following day but I'm don't remember exactly how I did it. I think it was that I added the "foreign" assembly in the IStyletIoCBuilder instance in the "ConfigureIoC" method of the Bootstrapper.
