### ISSUE TITLE
eventAggregator

### ISSUE THREAD

**Issue by UPeveryday** [canton7/Stylet#116]
Why does the Ihandle I subscribe to always trigger twice @canton7 @keichinger

**Comment by canton7** [comment]
You could have re-opened your previous issue, instead of opening two, you know...

Please provide code which reproduces your issue.

**Comment by UPeveryday** [comment]
Send： 
  public void ShowVoltageTestViewModels()
        {
            _eventAggregator.Publish("hello");//Send
            _windowManger.ShowDialog(_VoltageTestViewModel);
        }
Rec:
   public partial class VoltageTestViewModel : Screen,IHandle<string>
    {
        #region 
        public IEventAggregator _eventAggregator;
        public VoltageTestViewModel(IEventAggregator eventAggregator)
        {
            _eventAggregator = eventAggregator;
            _eventAggregator.Subscribe(this);
        }
        public void Handle(string message)
        {
                //When debugging, you will see the trigger twice，Only in my program
      //https://github.com/UPeveryday/-/blob/master/ViewModels/ParameterSettingViewModel.cs
        }

        #endregion


    }

**Comment by canton7** [comment]
I think you've got two separate instances of `VoltageTestViewModel`: one which is injected into `MainViewModel`, and one which is injected into `ParameterSettingViewModel`. I think you're getting confused by the breakpoint in `Handle(string message)` being hit twice, but it's being hit once in each instance. You can verify this by checking e.g. `this.GetHashCode()` in the watch window.

**Comment by UPeveryday** [comment]
Thank you. That's the question

**Comment by canton7** [comment]
Is your problem solved?

**Comment by UPeveryday** [comment]
Yes, thank you very much.

**Comment by canton7** [comment]
Glad to hear!

**Comment by canton7** [comment]
(To make the IoC container inject the same instance of `VoltageTestViewModel` into both `MainViewModel` and `ParameterSettingViewModel`, you can register it as singleton: `builder.Bind<VoltageTestViewModel>().ToSelf().InSingletonScope()`)

**Comment by UPeveryday** [comment]
Thank you. It's very practical
