### ISSUE TITLE
Crashes on loading main window in folder

### ISSUE THREAD

**Issue by micah686** [canton7/Stylet#118]
I'm not sure if this is the right place to ask this, but when I launch the program, it always seems to crash. Anyone have any idea what I'm doing wrong?
![image](https://user-images.githubusercontent.com/3616220/79300498-c0ecda80-7e9b-11ea-8f3a-a68eb7244088.png)

Boostrapper.cs
```cs
using Stylet;
using Tester.ViewModel;
namespace Tester
{
    public class Boostrapper: Bootstrapper<MainViewModel>
    {
    }
}
```
MainView.xaml
```xml
<Window x:Class="Tester.Views.MainView"       
       <!--cut content, standard xmlns -->
        Title="MainView" Height="450" Width="800">
    <Grid>        
    </Grid>
</Window>
```

MainViewModel.xaml
```cs
using Stylet;
namespace Tester.ViewModel
{
    public class MainViewModel: Screen
    {
        private readonly WindowManager _windowManager;

        public MainViewModel(IWindowManager windowManager)
        {
            _windowManager = (WindowManager)windowManager;
        }
    }
}

```

**Comment by canton7** [comment]
What exception does it throw?

Also, why cast the IWindowManager to WindowManager? Not that it should be causing a crash...

**Comment by micah686** [comment]
I get a ```Stylet.StyletViewLocationException: 'Unable to find a View with type Tester.View.MainView'```
And I was casting the window manager because I thought that was how I needed to do it, or should it just be IWindowManager?
I've attached the project as well.
[StyletTester.zip](https://github.com/canton7/Stylet/files/4482257/StyletTester.zip)

**Comment by canton7** [comment]
Aha. As the message says, it's looking for Tester.View.MainView, but your MainView is called Tester.View***s***.MainView.

You can change the namespace that MainView is in, or you can tell the ViewManager to look in Tester.Views, see `NamespaceTransformations` [here](https://github.com/canton7/Stylet/wiki/The-ViewManager#configuring-the-viewmanager).

Yes, the idea is that you use `IViewManager`. Then you can inject a mock ViewManager in your unit tests.

**Comment by micah686** [comment]
So, a few questions.
1)I would have to keep both the View and ViewModel folders singular or plural, not one of each, right?
2) Do I have to keep all of the Windows/UserControls in the View(s) root folder, or can I have them in a Views/Dialogs/ folder, for instance? I was having crashing trouble when I was testing additional windows out before, though I think they could just be this main issue.

**Comment by canton7** [comment]
1) Unless you set up your own name mappings, yes
2) You can have sub folders. The algorithm is [described here](https://github.com/canton7/Stylet/wiki/The-ViewManager#locating-a-view). So the View for ViewModels/Dialogs/FooViewModel.cs goes at View/Dialogs/FooView.xaml. Likewise Dialogs/ViewModels/Foo.cs and Dialogs/Views/Foo.xaml, or Dialogs/FooViewModel.cs and Dialogs/FooView.xaml. Simply take the name and namespace of the ViewModel and replace "ViewModel" with "View" to get the name and namesoace of the View.

**Comment by micah686** [comment]
So, all of the Views (Window, UserControl, Page,...) xaml files must end in ...View.xaml, and all of the associated Viewmodels must end in ...ViewModel.cs? Is that correct?

**Comment by canton7** [comment]
Yes, but this is configurable, see my first link. I strongly recommend reading the whole of that documentation page, as it answers many of the questions you've asked.

There's typically no need to use Page - navigation is done using other mechanisms in Stylet, see the docs.
