### ISSUE TITLE
GetErrors(null) in ValidatingModelBase always returns null

### ISSUE THREAD

**Issue by Kartoffelsalat2** [canton7/Stylet#119]
GetErrors(null) in ValidatingModelBase always return null. Even if HasErrors is true. But it should return a list of all errors.

**Comment by canton7** [comment]
Can you post code which reproduces the issue? See the samples for an example of `ValidatingModelBase` working

**Comment by Kartoffelsalat2** [comment]
If you add two lines to the example you can reproduce the error. In class UserViewModel in method OnValidationStateChanged add the following two lines

 var hasErrors = this.HasErrors;
 var allErrors = this.GetErrors(null);

allErrors is always zero even if hasErrors is true.

**Comment by canton7** [comment]
`GetErrors(null)` doesn't return all errors. It returns entity-level errors. [See these docs](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.inotifydataerrorinfo.geterrors?view=netframework-4.8#System_ComponentModel_INotifyDataErrorInfo_GetErrors_System_String_).

**Comment by Kartoffelsalat2** [comment]
Okay, thanks, I had that wrong.

**Comment by canton7** [comment]
Cool! No worries.
