### ISSUE TITLE
Custom usercontrol can not binding to itself xxViewModel

### ISSUE THREAD

**Issue by wanglehui** [canton7/Stylet#121]
Hi, Antony Male:
     Thank you for your remarkable first.
When i create new usercontrol and its matching xxViewModel in Library Project （HostShare）
and use it in other project （TurboGCS）， can not auto binding  correctly.
Look forward to your reply. Thanks in advance!

![2020-04-22_14-54-25](https://user-images.githubusercontent.com/2443832/79955875-f902a780-84b1-11ea-9d52-98a2a8d24c35.png)
![2020-04-22_14-53-36](https://user-images.githubusercontent.com/2443832/79955900-fef88880-84b1-11ea-9f0f-916584d911c8.png)

**Comment by canton7** [comment]
I'm afraid there isn't enough information to sa what your problem is.

Can you post your whole view? The small image you posted doesn't have the code `{s:Action SetFakeGPS}`, which is what's causing the issue.

**Comment by wanglehui** [comment]
I hope to find SetFakeGPS on UavStatusViewModel , may be in a wrong way.

<UserControl x:Class="HostShare.GUI.UavStatusView"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008" 
             xmlns:gui="clr-namespace:HostShare.GUI"
             xmlns:s="https://github.com/canton7/Stylet"
             mc:Ignorable="d" 
             d:DesignHeight="28" d:DesignWidth="800">

    <UserControl.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="Pack://application:,,,/HostShare;Component/Res/ImgRes.xaml"/>
                <ResourceDictionary Source="Pack://application:,,,/HostShare;Component/Res/BrushRes.xaml"/>
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </UserControl.Resources>
    
    <StackPanel Name="MainGrid" Orientation="Horizontal">
        <Rectangle Fill="{StaticResource BrushConnect}" Height="24" Width="24"></Rectangle>
        <Label VerticalContentAlignment="Center" Margin="1" Content="{Binding Connected}"/>

        <Rectangle Fill="{StaticResource BrushSignal}" Height="24" Width="24"></Rectangle>
        <Label VerticalContentAlignment="Center" Margin="1" Content="{Binding Connected}"/>
        
        <Rectangle Fill="{StaticResource BrushGPS}" Height="24" Width="24"></Rectangle>
        <Label VerticalContentAlignment="Center" Margin="1" Content="{Binding Connected}"
               MouseDoubleClick="{s:Action SetFakeGPS}"/>
        
        <Rectangle Fill="{StaticResource BrushBattery}" Height="24" Width="24"></Rectangle>
        <Label VerticalContentAlignment="Center" Margin="1" Content="{Binding Connected}"/>
        
        <Rectangle Fill="{StaticResource BrushTemperature}" Height="24" Width="24"></Rectangle>
        <Label VerticalContentAlignment="Center" Margin="1" Content="{Binding Connected}"/>
        
        <Rectangle Fill="{StaticResource BrushFlightMode}" Height="24" Width="24"></Rectangle>
        <Label VerticalContentAlignment="Center" Margin="1" Content="{Binding Connected}"/>
        
        <Rectangle Fill="{StaticResource BrushClimeRate}" Height="24" Width="24"></Rectangle>
        <Label VerticalContentAlignment="Center" Margin="1" Content="{Binding Connected}"/>
        
        <Rectangle Fill="{StaticResource BrushLock}" Height="24" Width="24"></Rectangle>
        <Label VerticalContentAlignment="Center" Margin="1" Content="{Binding Connected}"/>
        
        <Rectangle Fill="{StaticResource BrushOffGnd}" Height="24" Width="24"></Rectangle>
        <Label VerticalContentAlignment="Center" Margin="1" Content="{Binding Connected}"/>
        
        <Rectangle Fill="{StaticResource BrushCamera}" Height="24" Width="24"></Rectangle>
        <Label VerticalContentAlignment="Center" Margin="1" Content="{Binding Connected}"/>
        
        <Rectangle Fill="{StaticResource BrushBattery2}" Height="24" Width="24"></Rectangle>
        <Label VerticalContentAlignment="Center" Margin="1" Content="{Binding Connected}"/>

    </StackPanel>
</UserControl>

===============================================
<Controls:MetroWindow  
        xmlns:Controls="http://metro.mahapps.com/winfx/xaml/controls" 
        x:Class="TurboGCS.MainView"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:s="https://github.com/canton7/Stylet"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:gui="clr-namespace:HostShare.GUI;assembly=HostShare"
        mc:Ignorable="d"
        Title="MainView" Height="450" Width="800">

    <Grid x:Name="MainGrid">
        <Grid.ColumnDefinitions>
            <ColumnDefinition Width="5*"/>
            <ColumnDefinition Width="3"/>
            <ColumnDefinition Width="260" MaxWidth="400"/>
        </Grid.ColumnDefinitions>

        <Grid.RowDefinitions>
            <RowDefinition/>
            <RowDefinition Height="3"/>
            <RowDefinition/>
            <RowDefinition Height="36"/>
        </Grid.RowDefinitions>

        <GridSplitter Grid.Column="1" Grid.Row="0" Grid.RowSpan="3" HorizontalAlignment="Stretch" x:Name="VSplitter"/>
        <GridSplitter Grid.Column="2" Grid.Row="1" HorizontalAlignment="Stretch"/>
        <gui:UavStatusView Grid.Row="3" Grid.Column="0" Grid.ColumnSpan="3" Margin="-2 0 -2 0" BorderThickness="1"/>
        <Grid x:Name="RightPanel1"  Grid.Row="0" Grid.Column="2"/>
        <Grid x:Name="RightPanel2"  Grid.Row="2" Grid.Column="2">
            
        </Grid>
        <Grid x:Name="CenterPanel"  Grid.Row="0" Grid.Column="0" Grid.RowSpan="3"/>
    </Grid>
</Controls:MetroWindow>

**Comment by canton7** [comment]
That first bit of XAML you posted: is that from `UavStatusView`?
