### ISSUE TITLE
Guard Property is not being updated when binding to model

### ISSUE THREAD

**Issue by patrickiscoding** [canton7/Stylet#122]
So I have a 'form' in my app which is bound to a property in the VM called Login:

```
public class Login : PropertyChangedBase
    {
        private string username;
        private string password;

        public string Username { get => username; set => SetAndNotify(ref username, value);  }
        public string Password { get => password; set => SetAndNotify(ref password, value); }
    }
```

```
        public Login Login
        {
            get => login;
            set
            {
                if (SetAndNotify(ref login, value))
                {
                    NotifyOfPropertyChange(nameof(CanLoginClick));
                }
            }
        }
```

I have a guard property called CanLoginClick:
```
        public bool CanLoginClick =>
            !string.IsNullOrWhiteSpace(Login.Username) &&
            !string.IsNullOrWhiteSpace(Login.Password);
```

However, when Login.Username and Login.Password both are filled the button which action is `LoginClick()` is not being enabled while it should do that right?

```
<StackPanel VerticalAlignment="Center" Orientation="Vertical" Grid.Row="1" Grid.Column="1" >
            <TextBox x:Name="UsernameBox" Text="{Binding Login.Username, UpdateSourceTrigger=PropertyChanged}" Margin="5"  Foreground="White"
                     materialDesign:HintAssist.Hint="Username" />
            <TextBox Text="{Binding Login.Password, UpdateSourceTrigger=PropertyChanged}" Margin="5" Foreground="White"
                     materialDesign:HintAssist.Hint="Password">
            </TextBox>
                <Button x:Name="LoginButton" Command="{s:Action LoginClick}" Content="Login" Margin="5"/>
        </StackPanel>
```
This is how it is binded in the view.

**Comment by canton7** [comment]
You need to raise a PropertyChanged event for `CanLoginClick` when `Login.Username` or `Login.Password` is set, not when `Login` is set.

**Comment by patrickiscoding** [comment]
Ahh okay that works, is there an easier way to do this in the property itself?

**Comment by canton7** [comment]
You can do it if all of the properties are on the same object, but it gets harder if they're on different objects. You'd be better off putting `CanLoginClick` on the `Login` object. Of course, if you're using `Login` as something other than a ViewModel that's going to cause issues: this is why they say to have dedicated objects as ViewModels, and don't try and re-use them in other parts of your application.
