### ISSUE TITLE
IoC ToAbstractFactory "Duplicate type name" exception for same-name interfaces

### ISSUE THREAD

**Issue by TheMightyBorkon** [canton7/Stylet#123]
I'm having some problems with the `ToAbstractFactory()` extension method. In my particular scenario, the name of the interface that I'm trying to create an abstract factory for is "duplicated" but exists in two different namespaces. If I try to set up these bindings in the `ConfigureIoC` method I get an **ArgumentException** with the message "Duplicate type name within an assembly". This is from a reflection emit call which ultimately traces back to `StyletIoC.Internal.Container.GetFactoryForType(Type serviceType)`.

In a nutshell, if I have, say, an `IFactory` interface in two different namespaces (each with different methods), and I try to set up abstract factory bindings for them, then I get a runtime error. Is this a bug? I don't know, but it seems like a scenario that should be supported as the two interfaces ultimately have different full names (being in different namespaces).

Here's some test code to illustrate the issue:

```c#
using System;
using Stylet;
using StyletIoC;

namespace StyletTest.Foo
{
    public sealed class FooViewModel { }

    public interface IFactory
    {
        FooViewModel CreateFooViewModel();
    }

    public sealed class FactoryImpl : IFactory
    {
        public FooViewModel CreateFooViewModel() { throw new NotImplementedException(); }
    }

    public sealed class FooConductorViewModel
    {
        public FooConductorViewModel(IFactory factory) { }
    }
}

namespace StyletTest.Bar
{
    public sealed class BarViewModel { }

    public interface IFactory
    {
        BarViewModel CreateBarViewModel();
    }

    public sealed class FactoryImpl : IFactory
    {
        public BarViewModel CreateBarViewModel() { throw new NotImplementedException(); }
    }

    public sealed class BarConductorViewModel
    {
        public BarConductorViewModel(IFactory factory) { }
    }
}

namespace StyletTest
{
    public sealed class RootViewModel
    {
        public RootViewModel(Foo.FooConductorViewModel fooConductor, Bar.BarConductorViewModel barConductor) { }
    }

    public sealed class Bootstrapper : Bootstrapper<RootViewModel>
    {
        protected override void ConfigureIoC(IStyletIoCBuilder builder)
        {
            base.ConfigureIoC(builder);

            // The following two lines work (direct binding to implementations)
            //builder.Bind<Foo.IFactory>().To<Foo.FactoryImpl>();
            //builder.Bind<Bar.IFactory>().To<Bar.FactoryImpl>();

            // The following two lines fail at runtime (abstract factory bindings)
            builder.Bind<Foo.IFactory>().ToAbstractFactory();
            builder.Bind<Bar.IFactory>().ToAbstractFactory();
        }
    }
}
```

**Comment by canton7** [comment]
I can believe that: https://github.com/canton7/Stylet/blob/2b80db4db7d215f76855eafa3806c450fe532de5/Stylet/StyletIoC/Internal/Container.cs#L447

Should be an easy fix: copy [this](https://github.com/canton7/RestEase/blob/eeb07dcc09bac05550de4fdba772b97cb540a745/src/RestEase/Implementation/ImplementationBuilder.cs#L242).

**Comment by TheMightyBorkon** [comment]
Thanks for looking at this so quickly!

Really liking the library BTW: makes tricky things easier but isn't too prescriptive about it.

**Comment by canton7** [comment]
Awesome, glad you're enjoying it

**Comment by canton7** [comment]
Righty, that'll be on NuGet once it makes its way through their system

**Comment by TheMightyBorkon** [comment]
Worked like a charm, thank you

**Comment by TheMightyBorkon** [comment]
Just as an aside, the reason this came to light in the first place was because I noticed that most of my parent view models only created one or two different types of child view model, so I was ending-up with a lot of view model factory interfaces and naming them was becoming difficult!

Also, with the IoC binding, to simplify things I first created a marker interface to use with all of these view model factory interfaces:

```c#
public interface IIsViewModelFactory { }
```

Then was looking for something on the `IStyletIoCBuilder` that was like a cross between `ToAllImplementations()` and `ToAbstractFactory()`, so I could so something like:

```c#
builder.Bind<IIsViewModelFactory>().ToAllAbstractFactories();
```

but obviously that doesn't exist. :slightly_smiling_face:

In the end I went with this in `ConfigureIoC`:

```c#
foreach (Type factoryInterface in
    GetType().Assembly.GetExportedTypes().Where(IsViewModelFactory))
{
    builder.Bind(factoryInterface).ToAbstractFactory();
}
...
static bool IsViewModelFactory(Type type) =>
    type.Implements(typeof(IIsViewModelFactory)) && type != typeof(IIsViewModelFactory);
```

Then I can do this in each view model that requires a view model factory to create its children:

```c#
public sealed class ParentViewModel : Conductor<ChildViewModel>.Collection.OneActive
{
    public ParentViewModel(IViewModelFactory viewModelFactory)
    {
        ...
    }
    ...
    public interface IViewModelFactory : IIsViewModelFactory
    {
        ChildViewModel CreateChildViewModel();
    }
}
```

And after your change yesterday I no longer have to worry about giving each of these view model factory interfaces unique names! I can just call all of them `IViewModelFactory` and it works out because they are nested within their parent view model class.

**Comment by canton7** [comment]
I think I tried something similar at one point and moved away from it: the reason being that it completely messes up the "Go To Type" functionality in Visual Studio. You can't simply navigate to a type by typing its name. These days I like to have every type name by unique inside a project (and preferable the whole solution), to make navigation easier.
