### ISSUE TITLE
Support binding Actions to Commands programmatically

### ISSUE THREAD

**Issue by DaaWaan** [canton7/Stylet#124]
I have a ViewModel that has an `ICommand` property and would like to initialize the binding of that command property to a method using Actions in the ViewModel.

Something like:

    public class Page : Screen, INavigationPage
    {
        public ICommand Command => (ICommand)(new Action((PublishMyEvent)));
        . . .
        public void PublishMyEvent() => eventAggregator.Publish(new MyEvent());
    }

**Comment by canton7** [comment]
Why not use [actions](https://github.com/canton7/Stylet/wiki/Actions)?

**Comment by DaaWaan** [comment]
I mean yeah, I'm referring to the [Actions](https://github.com/canton7/Stylet/wiki/Actions) from this framework. It's just that the examples are done in xaml. Does the framework provide a way to do it in code?

**Comment by DaaWaan** [comment]
I'm binding the Command property above in a style for an ItemsControl inside a CustomControl.

     . . .
    <Style TargetType="{x:Type ItemsControl}">
        <Setter Property="ItemTemplate">
            <Setter.Value>
                <DataTemplate>
                    <local:Item Command="{Binding Command}" Icon="{Binding Icon}" />
                </DataTemplate>
            </Setter.Value>
        </Setter>
    </Style>
    . . . 

Since the `{s:Action MethodName}` doesn't work in Styles, I'm finding a way if Stylet's action can work in code-behind. Something similar to my first comment.

**Comment by canton7** [comment]
Ah right. You'll have to write your own ICommand implementation. They're pretty straightforward.
