### ISSUE TITLE
IStyletIoCBuilder is not working

### ISSUE THREAD

**Issue by hdzs** [canton7/Stylet#130]
Here are your instructions：
// First, create the builder
var builder = new StyletIoCBuilder();

// Configure the builder
builder.Bind<IVehicle>().To<HotHatchback>();

// The container is then built for you

// Now you can use this to resolve instances of services
var vehicle = ioc.Get<IVehicle>();

But I did not find the relevant interface（ioc.get???）, is it because of the version problem?Below is my screenshot：
![image](https://user-images.githubusercontent.com/39402049/81536353-f9e67500-939d-11ea-8b11-adc722ab0ba0.png)

**Comment by canton7** [comment]
I'm not sure where you got those instructions from, but the line you're missing is:

```cs
var ioc = builder.BuildContainer();
```

The bootstrapper does this for you, and sets the `container` property on `Bootstrapper<T>`
