### ISSUE TITLE
Using Stylet in a class library

### ISSUE THREAD

**Issue by sa-mustafa** [canton7/Stylet#131]
I want to ship a library containing WPF views based on Stylet MVVM approach. How can I bootstrap the library? Suppose, the caller does not know and does not want to know, how to work with Stylet.

The default bootstrapper takes a ViewModel and shows it by default which is not desirable in a class library. I resorted to modifying (which is not preferable) the Stylet's source by adding a ViewModel-less bootstrapper. I hit other errors such as Bootstrapping twice (when the library is used in another project using the Stylet too) at this [line](https://github.com/canton7/Stylet/blob/9675bc5d9b00fff7eafc49f682a34c004a6f1dab/Stylet/BootstrapperBase.cs#L78). I believe there should be an elegant way to use Stylet in a class library, bootstrapping without showing a default ViewModel, calling the [Bootsrapper's Start](https://github.com/canton7/Stylet/blob/9675bc5d9b00fff7eafc49f682a34c004a6f1dab/Stylet/BootstrapperBase.cs#L48) in a well-defined manner without adding it to the caller App's Resources.
Another suggestion is to modify the WindowManager class and make a public [CreateWindow](https://github.com/canton7/Stylet/blob/9675bc5d9b00fff7eafc49f682a34c004a6f1dab/Stylet/WindowManager.cs#L176) function so that anyone can modify the window's properties such as positioning. The [ShowDialog](https://github.com/canton7/Stylet/blob/9675bc5d9b00fff7eafc49f682a34c004a6f1dab/Stylet/WindowManager.cs#L125) function may be modified to give back a Window object and let the caller show it.
Thanks a lot for the library.

**Comment by canton7** [comment]
How would the user of your class library actually interact with it?

Is the intention that they'd write their own views and viewmodels, which can make use of the ones in your class library? Or perhaps they have their windows, they can ask your library to show your windows, and those don't interact? Or perhaps they don't have any of their own views/models?

**Comment by sa-mustafa** [comment]
It's the second case. They have their own, and I would like to provide the library based on Stylet MVVM pattern. After a day of struggling with the library, I switched to the Stylet source code and saw the inter working. I figured a way to solve my problems. I've come up with the following ViewModel-free bootstrapper:
```C#
namespace Bps.Osk
{
    using System.Windows;

    public class Bootstrapper : Stylet.Bootstrapper<object>
    {
        public static Bootstrapper Instance
        {
            get
            {
                if (bootstrapper != null)
                    return bootstrapper;

                bootstrapper = new Bootstrapper();
                bootstrapper.Setup(App.Current);
                bootstrapper.Configure();
                return bootstrapper;
            }
        }
        private static Bootstrapper bootstrapper;

        protected static Stylet.IViewManager ViewManager
        {
            get
            {
                if (viewManager != null)
                    return viewManager;

                viewManager = Instance.GetInstance(typeof(Stylet.IViewManager)) as Stylet.IViewManager;
                return viewManager;
            }
        }
        private static Stylet.IViewManager viewManager;

        protected static Stylet.IWindowManager WindowManager
        {
            get
            {
                if (windowManager != null)
                    return windowManager;

                windowManager = Instance.GetInstance(typeof(Stylet.IWindowManager)) as Stylet.IWindowManager;
                return windowManager;
            }
        }
        private static Stylet.IWindowManager windowManager;

        public new void Configure()
        {
            ConfigureBootstrapper();
        }

        public Window CreateWindow(object viewModel)
        {
            var view = ViewManager.CreateAndBindViewForModelIfNecessary(viewModel);
            return view as Window;
        }
    }
}
```
The library user just needs to create his desired ViewModel by calling the Bootstrapper.Instance.CreateWindow function. The library & stylet is automatically boostrapped and the ViewModel is shown correctly. If you agree with the solution, please add some notes to the documentation. 
The need for a public CreateWindow function still remains.

**Comment by canton7** [comment]
I'm not sure how that can work? You're passing in `App.Current`, which is the App you've defined in your class library, not the actual running App.

I'd probably attempt something like the following (untested):

```cs
public class MyBootstrapper : Bootstrapper<object>
{
    // Stop it showing a window on startup
    protected override void Launch() { }
    // Expose the IContainer
    public new IContainer Container => base.Container;
}

public class LibraryManager
{
    private readonly MyBoostrapper bootstrapper;

    public LibraryManager
    {
        this.boostrapper = new MyBootstrapper();
        this.bootstrapper.Setup(Application.Current);
        // Might need to call OnStart as well, if the application has already started?
    }

    public void ShowWindow(MyViewModelBaseClass viewModel)
    {
        var windowManager = this.bootstrapper.Container.Get<IWindowManager>();
        windowManager.ShowWindow(viewModel);
    }
}
```

**Comment by sa-mustafa** [comment]
Yeah, you're right about `App.Current`; it should be changed to `Application.Current`. However, either code does the job.
Do you provide a public `CreateWindow` function? Sometimes, the caller need the `Window `object prior to display.

**Comment by canton7** [comment]
Stylet is a VM-first framework: you shouldn't really be interacting directly with views or windows.

That said, WindowManager [has a protected CreateWindow method](https://github.com/canton7/Stylet/blob/9675bc5d9b00fff7eafc49f682a34c004a6f1dab/Stylet/WindowManager.cs#L176): if you want to customise how windows are created, subclass WindowManager to create your own customised version.
