### ISSUE TITLE
invalid binding！

### ISSUE THREAD

**Issue by hdzs** [canton7/Stylet#132]
<Button Command="{s:Action UploadProgram}"  Style="{StaticResource buttonStyleOpacity}" >
            <svgc:SvgViewbox Source="/Images/SecondaryPage/program.svg" Width="100" Height="70" Stretch="Fill" Margin="5"/>

   </Button>

After I added this style to the xaml file, my binding was invalid ...
After testing, I found that after removing the reference to the svg file, the binding worked again.
I think this is not the root cause, because I have loaded svg files on other pages, and this problem has not occurred. The reference to load the svg file is "http://sharpvectors.codeplex.com/svgc/"

[program.txt](https://github.com/canton7/Stylet/files/4688719/program.txt)

**Comment by canton7** [comment]
Are you sure this is a Stylet issue?

If you are, please provide the code necessary to understand your problem. I don't what "the xaml file" or "my binding" are.

**Comment by canton7** [comment]
Closing as no response
