### ISSUE TITLE
IWindowManager.ShowWindow throws NullReferenceException

### ISSUE THREAD

**Issue by jsimunac** [canton7/Stylet#134]
I'm attempting my first project using Stylet.  I created my initial view.  The user enters information and retrieves information from the database.  This all works fine - I can trace and see all the models being populated.  When I try to open the second view/viewmodel using IWindowManager.ShowWindow I get a NullReferenceException.  I'm following the documentation exactly to open the next window.  When I instantiate the new viewmodel, it runs InitializeCommand and all models for the second viewmodel are populated as well.  But the ShowWindow doesn't work.  Could you please give me some advice, or an example?  Thanks!

**Comment by canton7** [comment]
Do you have anything on `OnActivate` / `OnInitialActivate`?

Can you create a minimal reproducible example which shows the problem, and post it?

**Comment by jsimunac** [comment]
Nothing in OnActivate / OnInitialActivate.  I'll try to set up a small example tomorrow when I get in to work.  Thanks!

**Comment by jsimunac** [comment]
Here is a small example.  The first form has a button.  Click it and it loads some data and calls the second viewmodel.  The data from is loaded, but the window is not shown.  Please let me know if you need anything else.  Thanks for any help you can give.

[ShowWindowTest.zip](https://github.com/canton7/Stylet/files/4798797/ShowWindowTest.zip)

**Comment by canton7** [comment]
Your `WindowManager` is null:

![image](https://user-images.githubusercontent.com/568104/85063560-3af25600-b1a2-11ea-9ae4-7071850023ba.png)

If we look at the field declaration, we can see that it's never assigned to:

![image](https://user-images.githubusercontent.com/568104/85063622-4fcee980-b1a2-11ea-857e-7f47f8dafa2b.png)

If we fix up the constructor to have an `IWindowManager` injected into it, and assign that to our field, things work:

```cs
public ShellViewModel(IWindowManager windowManager)
{
    WindowManager = windowManager;
}
```

**Comment by jsimunac** [comment]
Thank you.  That did it.  I actually had that in my original project, but had a lower case instead of upper case W when setting it, and that's why it was never assigned.  I feel so dumb!
