### ISSUE TITLE
怎么使用全局样式？

### ISSUE THREAD

**Issue by zqstdy** [canton7/Stylet#137]
```
<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
                    xmlns:local="clr-namespace:xx.Style">
    <Style TargetType="Window">
        <Setter Property="Background" Value="#ccc"/>
    </Style>
</ResourceDictionary>
```
不设置key默认会应用到所有窗口 
现在使用了stylet后没有效果了

**Comment by canton7** [comment]
Google translate says:

> How to use global styles
> 
> Do not set the key will be applied to all windows by default
> Now no effect after using stylet

Have you seen [this doc](https://github.com/canton7/Stylet/wiki/Bootstrapper#adding-resource-dictionaries-to-appxaml)?

**Comment by zqstdy** [comment]
这个看过，我也加了字典的资源引用，在编辑模式下显示也正常，就是运行起来没效果了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Antony Male"<notifications@github.com&gt;; 
发送时间: 2020年7月3日(星期五) 下午5:04
收件人: "canton7/Stylet"<Stylet@noreply.github.com&gt;; 
抄送: "鱼"<zqstdy@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [canton7/Stylet] 怎么使用全局样式？ (#137)





 
谷歌翻译说：
  
如何使用整体风格
 
不设置键默认情况下将应用于所有窗口
 现在使用stylet后无效
  
你看过这个文件吗？
 
— 
您收到此消息是因为您创建了线程。
直接回复此电子邮件，在GitHub上查看，或取消订阅。

**Comment by canton7** [comment]
Google translate says:

> I have seen this, and I have added the resource reference of the dictionary, and the display is normal in edit mode, but it has no effect when it runs.

I'm afraid I need to see some more code, then. Can you post a project which reproduces your problem?

**Comment by zqstdy** [comment]
在VS 调试模式可以看到背景颜色，运行之后背景色没了






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Antony Male"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月3日(星期五) 下午5:21
收件人:&nbsp;"canton7/Stylet"<Stylet@noreply.github.com&gt;;
抄送:&nbsp;"鱼"<zqstdy@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [canton7/Stylet] 怎么使用全局样式？ (#137)





 
Google translate says:
  
I have seen this, and I have added the resource reference of the dictionary, and the display is normal in edit mode, but it has no effect when it runs.
  
I'm afraid I need to see some more code, then. Can you post a project which reproduces your problem?

**Comment by zqstdy** [comment]
[Test.zip](https://github.com/canton7/Stylet/files/4869152/Test.zip)

**Comment by canton7** [comment]
I don't know why this is happening, but the same thing happens in a WPF project without Stylet, so I don't think it's anything to do with Stylet.

[Test.zip](https://github.com/canton7/Stylet/files/4872757/Test.zip)

**Comment by zqstdy** [comment]
net core bug……

**Comment by canton7** [comment]
I saw the same thing .NET Framework

**Comment by zqstdy** [comment]
好奇怪，记得以前就这么写的……是我记错了吗？

**Comment by canton7** [comment]
Google translate says:

> It's so strange, I remember writing this before... Am I remembering it wrong?

I'm not sure I'm afraid - I don't think I've ever tried to do this before now.
