### ISSUE TITLE
How can I custom the TabItem style 

### ISSUE THREAD

**Issue by zredb** [canton7/Stylet#141]
Hello, 

as the sample shows as [below:](https://github.com/canton7/Stylet/wiki/Screens-and-Conductors)
      
how can i custom the TabItem styles? this template change the TabItem to ContentControl, but custom the ContentControl to TabItem style is not so simple. and where is the location of StyletConductorTabControl location? thank you.

**Comment by canton7** [comment]
The [GitHub search box](https://github.com/canton7/Stylet/search?q=StyletConductorTabControl&unscoped_q=StyletConductorTabControl) leads you to [this](https://github.com/canton7/Stylet/blob/a40a27fd146a4680e9eafddd262a2e3fbf7fedbe/Stylet/Xaml/StyletResourceDictionary.xaml#L17): is that what you were after?

In fact, the [very page you linked to](https://github.com/canton7/Stylet/wiki/Screens-and-Conductors) gives you the equivalent XAML:

```xaml
<TabControl ItemsSource="{Binding Items}" SelectedItem="{Binding ActiveItem}" DisplayMemberPath="DisplayName">
   <TabControl.ContentTemplate>
      <DataTemplate>
         <ContentControl s:View.Model="{Binding}" VerticalContentAlignment="Stretch" HorizontalContentAlignment="Stretch" IsTabStop="False"/>
      </DataTemplate>
   </TabControl.ContentTemplate>
</TabControl>
```

**Comment by canton7** [comment]
Closing as no response.
