### ISSUE TITLE
WindowManager.ShowDialog never returns nulled bool

### ISSUE THREAD

**Issue by pingu2k4** [canton7/Stylet#142]
From a window requesting close after having been opened with ShowDialog on WindowManager, the returned result from ShowDialog will never be null. I tried `RequestClose();` and `RequestClose(null);` and both instead return false.

**Comment by canton7** [comment]
`WindowManager.ShowDialog` just wraps WPF's `Window.ShowDialog()`, and returns the same value. Calling `RequestClose(x)` sets the window's `DialogResult` to `x`. 

From [the docs](https://docs.microsoft.com/en-us/dotnet/api/system.windows.window.showdialog?view=netcore-3.1#remarks), it looks like `Window.ShowDialog()` will never return null, which means that `WindowManager.ShowDialog` will never return null. I don't think there's anything I can do about this: changing the signature of that method would be a breaking change.

**Comment by canton7** [comment]
Closing as no response.
