### ISSUE TITLE
How can i raise TextBox KeyDown event?

### ISSUE THREAD

**Issue by CodingOctocat** [canton7/Stylet#143]
I try:
```
<TextBox KeyDown="{s:Action MyKeyDown}" />
```

```
private void MyKeyDown(object sender, KeyEventArgs e)
{
    // stuff...
}
```
doesn't work.

**Comment by canton7** [comment]
What does "doesn't work" mean? What exactly happens, which makes you think that it doesn't work?

**Comment by kaisame** [comment]
The bind method is not running,MyKeyDown method do not response.

**Comment by canton7** [comment]
It works for me. Here's a project which demonstrates it working:

[TestProject.zip](https://github.com/canton7/Stylet/files/5168928/TestProject.zip)

Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) which demonstrates your issue.

**Comment by kaisame** [comment]
TestProject.zip MykeyDown method only response ''enter','alt','crtl' ,'window' event.

**Comment by canton7** [comment]
I don't know what you're trying to say I'm afraid.

Maybe you want the PreviewKeyDown event?

**Comment by kaisame** [comment]
thanks.That is what I need
