### ISSUE TITLE
Button not enabling when its CanX property returns true

### ISSUE THREAD

**Issue by trustieee** [canton7/Stylet#148]
Reproduced in this repo here: https://github.com/mariocatch/stylet-foo

I'm using the default Stylet template with dotnet core 3.1.
I simply added a property/method for reproducing the issue.

```xml
<TextBox Text="{Binding Username, 
                Mode=TwoWay, 
                UpdateSourceTrigger=PropertyChanged}" 
         Width="100" Height="100"/>

<Button Command="{s:Action Do}">Foo</Button>
```
```cs
public class ShellViewModel : Screen
{
    public string Username { get; set; }

    public void Do() { }

    public bool CanDo => !string.IsNullOrWhiteSpace(Username);
}
```

Breakpoint on `CanDo` property is hit once and never hit again. Changing the value in the `TextBox`, while calling `set`, does not retrigger the `CanDo` property.

I've also tried using backing fields with `SetAndNotify`, to no avail:
```cs
public string Username { get => username; set => SetAndNotify(ref username, value, nameof(Username)); }
```

**Comment by mariocatch** [comment]
I realize I am missing property changed notifications. Through all of the examples I saw I assumed this was handled implicitly by Stylet for me.

After changing my property setters to the following, it works as expected.
```cs
public string Username
{
    get => _username;
    set
    {
        SetAndNotify(ref _username, value);
        NotifyOfPropertyChange(() => CanLogin);
    }
}
```

**Comment by canton7** [comment]
Yes, you'll need to raise an INPC event for `CanLogin` whenever `Username` changes. I'll make sure the wiki makes this clear.

I normally wire things together in the constructor:

```cs
Bind(s => s.Username, (o, e) => NotifyOfPropertyChange(nameof(CanLogin)));
```

**Comment by canton7** [comment]
Re-opening as a reminder to improve the docs

**Comment by haven1433** [comment]
I'd be happy to handle the wiki change if you'd like

**Comment by canton7** [comment]
Sure, please go ahead!

**Comment by haven1433** [comment]
Updated https://github.com/canton7/Stylet/wiki/PropertyChangedBase examples to include the "wire in constructor" version and replaced the update-in-method examples with update-in-property examples to make it more clear. If you're happy with the changes, please close this issue.

**Comment by ShemJM** [comment]
Hi, I have a question regarding Guard Properties. Wasn't sure where to ask but this thread seems kind of related.

How can I pass the CommandParameter into a guard property? So a button would be enabled/disabled depending on the state of the bound model.

**Comment by canton7** [comment]
@haven1433 Thank you!

@ShemJM That's a limitation of guard properties. It's probably easiest to bind that thing to another property in the VM, and inspect it from your guard property's getter. Make sure you raise the appropriate INPC evets.

**Comment by ShemJM** [comment]
@canton7 Thanks. I'll give it a go and thanks for Stylet!

**Comment by canton7** [comment]
The wiki page on guards now uses INPC throughout
