### ISSUE TITLE
why window manager ‘s ShowMessageBox can't popup in OnExit method?

### ISSUE THREAD

**Issue by zredb** [canton7/Stylet#149]
I want to implement the function when quit the app, program query the user weather save changes, bug these code can't work:
 protected override void OnExit(ExitEventArgs e)
        {
               var wm= kernel.Get<WindowManager>();
               var dr=wm.ShowMessageBox("Project has change, do you want to save it?","", MessageBoxButton.YesNo); 
               if (dr == MessageBoxResult.Yes) 
                //do something,
         }
can anyone give any sugesstion?

**Comment by canton7** [comment]
Perhaps because it's too late and the application is already shutting down? I'm in mobile so can't test.

I recommend overriding `CanCloseAsync` in your shell ViewModel, and putting your logic in there.

**Comment by zredb** [comment]
Thank you for your quick reply, I will try to use it, thank you.

**Comment by canton7** [comment]
Great. Please re-open if you still have issues.
