### ISSUE TITLE
Unable to find a View with type MyApplication.Views.First.OneView

### ISSUE THREAD

**Issue by FaustPipeDream** [canton7/Stylet#150]
I'm using  `WindowManager.ShowWindow`  open a new window. At first, It work fine,But after I change the namespace of the `OneViewModel`  from  `MyApplication.ViewModels` to `MyApplication.ViewModels.First`.  this error occur,And it work again after the namespace back to `MyApplication.ViewModels `

**Comment by FaustPipeDream** [comment]
I found the ViewModel can't change namespace after create, but why?

**Comment by canton7** [comment]
The name and namespace of the View had to match the ViewModel. Please read [this doc](https://github.com/canton7/Stylet/wiki/The-View Manager)

**Comment by FaustPipeDream** [comment]
> The name and namespace of the View has to match the ViewModel. Please read [this doc](https://github.com/canton7/Stylet/wiki/The-ViewManager)
Yeah, That's a namespace problem,I see. The namespace of the View is not match the VeiwMdel.Thank you.
