### ISSUE TITLE
Issue with datcontext/binding

### ISSUE THREAD

**Issue by micah686** [canton7/Stylet#155]
I'm having trouble setting up certain types of XAML Binding, so that I can right click on the property/Command, and go to the relevant section on the ViewModel.
For example:
```xml
<UserControl....
xmlns:viewModels="clr-namespace:VnManager.ViewModels"
mc:Ignorable="d" 
 d:DataContext="{d:DesignInstance viewModels:RootViewModel}"
>
<Grid Grid.Column="0" x:Name="GrdSideBar">
                    <Grid.RowDefinitions>
                        <RowDefinition Height="160"/>
                        <RowDefinition Height="90*"/>
                        <RowDefinition Height="40"/>
                    </Grid.RowDefinitions>
                    <ContentControl Grid.Row="0" s:View.Model="{Binding LastPlayedPage}"/>
                    <ContentControl Grid.Row="1" s:View.Model="{Binding CategoryListPage}"/>
                    <ContentControl Grid.Row="2" s:View.Model="{Binding AddGamePage}"/>
                </Grid>
</UserControl>
```

```cs
public LastPlayedViewModel LastPlayedPage { get; set; }
public CategoryListViewModel CategoryListPage { get; set; }
public AddGameButtonViewModel AddGamePage { get; set; }
```

With the code above, I get a :
```
Cannot resolve property 'LastPlayedPage ' in data context of type MyAppName.ViewModels.RootViewModel.
```

Is there also a way to have the methods used in the s:Action _____ show up in the view model as being used?
So something like Command="{s:Action SubmitAsync} would have the SubmitAsync command in the ViewModel shown as being referenced?
Or does that go against the design principles of Stylet?

**Comment by canton7** [comment]
Those properties you posted, are they from `RootViewModel`? WPF doesn't think that `RootViewModel` has a property called `LastPlayedPage ` (that trailing space might or might not be significant, I'm not sure). This is a WPF issue anyway, not a Stylet one.

> Is there also a way to have the methods used in the s:Action _____ show up in the view model as being used?

I don't know of any. Let me know if you find one!

**Comment by micah686** [comment]
No, it's from a custom UserControl that I've made, not the RootViewModel.

**Comment by canton7** [comment]
The DataContext at that point is RootViewModel though, as you can see from the binding error. From the small snippet you posted it's not clear why you think the DataContext should be anything else.

Can you post a complete minimal reproducible sample, so I can see what you're actually trying to do? At the moment there simply isn't enough information to give any help.

**Comment by micah686** [comment]
Nevermind, I'm blind. I was using the RootViewModel as the datacontext, instead of the associated VM class.
