### ISSUE TITLE
How can i use s:Action as event handler？

### ISSUE THREAD

**Issue by wanglehui** [canton7/Stylet#156]
Hi，canton7

When i bind control event handler to s:Action XX funtion, how can set CommnadParameter to event parameter? Some thing like EventToCommand Behavior.

**Comment by canton7** [comment]
When you're using an event with `s:Action`, there is no concept of `CommandParameter`: there's no way to pass one in the XAML, and no way of getting one back in the C#. I recommend binding whatever property you're interested in to a property on your ViewModel.

**Comment by canton7** [comment]
Closing as no response
