### ISSUE TITLE
About CanExecute Err!

### ISSUE THREAD

**Issue by wf-soft** [canton7/Stylet#157]
Hi! @canton7 
How to handle "bool Canxxx = > View.xxx" This exception is initialized to null.

![image](https://user-images.githubusercontent.com/62228539/93658353-6e78a100-fa6d-11ea-9872-1e58a7485788.png)

If I use datagroupv?. DG SelectedItems.Count ==1; popup's MenuItem will be disabled forever and cannot be refreshed

**Comment by canton7** [comment]
As the message says, `DataGroupV` is null, so calling `DataGroupV.dg` gives you a `NullReferenceException`. 

> If I use datagroupv?. DG SelectedItems.Count ==1; popup's MenuItem will be disabled forever and cannot be refreshed

You'll have to debug why that is.

I'm afraid this isn't a question specifically about Stylet: you'll get much better support somewhere else, like StackOverflow.
