### ISSUE TITLE
AutofacBootstrapper causes multiple Dispose of VMs and Self

### ISSUE THREAD

**Issue by azabluda** [canton7/Stylet#16]
I think these registrations are lacking [ExternallyOwned](https://autofac.org/apidoc/html/6F9EA0B.htm) specification
```cs
protected virtual void DefaultConfigureIoC(ContainerBuilder builder)
{
    var viewManagerConfig = new ViewManagerConfig()
    {
        ViewFactory = this.GetInstance,
        ViewAssemblies = new List<Assembly>() { this.GetType().Assembly }
    };
    builder.RegisterInstance<IViewManager>(new ViewManager(viewManagerConfig));

    builder.RegisterInstance<IWindowManagerConfig>(this); // <<< causes 'this' to Dispose twice
    builder.RegisterType<WindowManager>().As<IWindowManager>().SingleInstance();
    builder.RegisterType<EventAggregator>().As<IEventAggregator>().SingleInstance();
    builder.RegisterType<MessageBoxViewModel>().As<IMessageBoxViewModel>(); // <<< okay, but only as long as MessageBoxViewModel implements no IDisposable
    builder.RegisterAssemblyTypes(this.GetType().Assembly); // <<< both Stylet and Autofac will dispose every ViewModel implementing IDisposable
}
```

**Comment by canton7** [comment]
Aha thanks, I'm not too familiar with autofac.

**Comment by azabluda** [comment]
Same as myself unfamiliar with other containers... And since nobody is able to know all of them anyway, wouldn't it be safer to just cover those cases by unit tests?

**Comment by canton7** [comment]
> `builder.RegisterAssemblyTypes(this.GetType().Assembly); // <<< both Stylet and Autofac will dispose every ViewModel implementing IDisposable`

I don't think that's right - Stylet doesn't dispose transient instances.

**Comment by azabluda** [comment]
@canton7 In our pseudo-MDI application we dynamically create VMs (resolve instances from IoC) and add them to `Conductor<T>.Collection.OneActive`. These VMs are presented as tabs on the UI. The VMs allocate some resources, so they implement `IDisposable` to perform the necessary cleanup. When the tab is closed, we call `Conductor<T>.Collection.OneActive.CloseItem` which in turn triggers `VM.Dispose` as part of `StyletConductorExtensions.CloseAndCleanUp` logic.

This behavior looks absolutely correct, BUT surprisingly we observe another call to `VM.Dispose` during app shutdown because Autofac (configured to own every resolved object implementing `IDisposable` because no `ExternallyOwned` is specified) is cleaning its items too.

**Comment by canton7** [comment]
Aha, gotcha. I think the changes I made just above fix this.
