### ISSUE TITLE
use   <ResourceDictionary> 

### ISSUE THREAD

**Issue by Zellear** [canton7/Stylet#165]
![图像_2020-11-07_070836](https://user-images.githubusercontent.com/52039441/98422941-0d159b80-20c8-11eb-9e14-a282334cf5ae.png)

Using the dictionary resources <ResourceDictionary> app.xaml, the program does not start, ask what is the reason

**Comment by canton7** [comment]
Please read [this part of the documents](https://github.com/canton7/Stylet/wiki/Quick-Start#the-applicationloader)

**Comment by Zellear** [comment]
That’s right，thanks a lot！

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Antony Male<mailto:notifications@github.com>
发送时间: 2020年11月8日 3:57
收件人: canton7/Stylet<mailto:Stylet@noreply.github.com>
抄送: Zeller<mailto:ice_nell@live.cn>; Author<mailto:author@noreply.github.com>
主题: Re: [canton7/Stylet] use <ResourceDictionary> (#165)


Please read this part of the documents<https://github.com/canton7/Stylet/wiki/Quick-Start#the-applicationloader>

―
