### ISSUE TITLE
Added an introductory example

### ISSUE THREAD

**Issue by ShuhuaGao** [canton7/Stylet#171]
Hi,

I am new to MVVM in WPF. After playing with several frameworks like MVVMCross and ReactiveUI, I feel that Stylet is the most straightforward and easy-to-use one since it does not involve a lot of *magic*. Thank you.

I want to make some contribution and thus write an introductory example from a beginner's perspective, which I believe is quite friendly to complete beginners. The tutorial is posted to the Wiki [here](https://github.com/canton7/Stylet/wiki/Introductory-example:-a-guest-book-application). However, I don't know how to add a link to it in the sidebar. Could you make it? I will keep improving the tutorial.

**Comment by sigmarsson** [comment]
You can utilize the Fody injector to have all your properties notified by its weaver. @canton7 was exhibiting it in a demo earlier so you can watch how he accomplished that.

**Comment by ShuhuaGao** [comment]
Hi, @sigmarsson , yes, you are totally right. I am aware of Fody. However,  I am aiming to prepare a tutorial for a **beginner** of WPF/MVVM (like myself a week ago), and thus I avoid Fody intentionally to reduce the magic behind. I may add it in the *advanced* part.

**Comment by canton7** [comment]
Thanks for putting in that effort! How does this compare to the pre-existing tutorial at https://github.com/canton7/Stylet/wiki/1.-Introduction (which I don't think I ever got around to finishing, sadly)?

**Comment by ShuhuaGao** [comment]
Hi, @canton7. Personally, I think that the tutorial I prepared is more detailed (almost every line is explained), beginner-friendly (I also explain some operations in Visual Studio), and up-to-date. You may keep both if needed. 

Besides, as for the *Samples* in this repository, I cannot make them run in my Visual Studio 2019. For example, starting the  *Stylet.Samples.Hello* project results in errors:
![Snipaste_2020-11-21_21-06-08](https://user-images.githubusercontent.com/20141984/99878034-68ee3180-2c3d-11eb-9ee9-830a4309d8bb.png)

It seems some configuration changes are needed, but I am not clear how to do it.

**Comment by canton7** [comment]
Sorry for not responding -- this slipped under my radar.

Is there somewhere else you could host this, where I could link to?

The problem with making it part of the wiki is that it then becomes my responsibility. This means I need to vouch for its correctness, and also update it when changes are made.

**Comment by ShuhuaGao** [comment]
Hi, @canton7. I am afraid that the example is a little outdated w.r.t the current version of Stylet. No need to maintain it now. Please feel free to remove it from your wiki (I don't know how to do it though).
