### ISSUE TITLE
Does `Stylet.Start` scaffold package supports .net 5?

### ISSUE THREAD

**Issue by GF-Huang** [canton7/Stylet#173]
I don't prefer to use command line for creating project in windows visual studio.

**Comment by canton7** [comment]
Stylet.Start only supports .NET Framework, not .NET Core (and .NET 5 is just reskinned .NET Core, although I should make that clearer in the docs).

I'm not sure whether Stylet works on .NET 5 (need to test), but you will need to use Stylet.Templates. As of recent VS 16.2 Preview 8, [there's an option to make the CLI templates show up in the New Project window](https://devblogs.microsoft.com/dotnet/net-cli-templates-in-visual-studio/).

**Comment by GF-Huang** [comment]
OK, thanks.
