### ISSUE TITLE
Incompatible with Telerik.RadWindow

### ISSUE THREAD

**Issue by GF-Huang** [canton7/Stylet#175]
![image](https://user-images.githubusercontent.com/4510984/100099104-ee6e1d80-2e99-11eb-9b5f-410c2d2198c1.png)

**Comment by canton7** [comment]
Stylet doesn't know how to show a `RadWindow`, and there's no way to teach it without adding a dependency on Telerik, but then everyone who used Stylet would have to download and reference Telerik!

You'll have to create your own version of `WindowManager` which knows how to show a `RadWindow`. You can take inspiration from [WindowManager](https://github.com/canton7/Stylet/blob/master/Stylet/WindowManager.cs).
