### ISSUE TITLE
Can s:Action bind to static methods?

### ISSUE THREAD

**Issue by GF-Huang** [canton7/Stylet#177]

**Comment by canton7** [comment]
No, noone's ever asked for that. Is that something you need? I'm not sure how it would work...

**Comment by GF-Huang** [comment]
In WPF, sometimes we have a global `AppCommands` for global commands. Add the `<AppCommands key="AppCommands" />` to the `App.xaml` for global use is messier. So I want to make the `AppCommands` methods to static.

![image](https://user-images.githubusercontent.com/4510984/100359046-fbbe1000-3031-11eb-9d74-44adaf124349.png)

**Comment by canton7** [comment]
What would the syntax look like? `{s:Action Thingy, Target={x:Type app:Something}}`?

**Comment by canton7** [comment]
We won't be able to make that work with guard proerties in this case however

**Comment by GF-Huang** [comment]
Maybe like `{s:StaticAction xxx:AppCommands.ShowRootViewCommand}`?

**Comment by canton7** [comment]
That would have to be passed as a string, and I can't parse the `xxx` prefix from a string. I'd need to pass in a Type generated from an `x:Type` somewhere (I don't think `x:Static` can be used to refer to a method group)

**Comment by GF-Huang** [comment]
It seems implements, great!

**Comment by canton7** [comment]
It is. I'll write up how to use it in the wiki when I get some time
