### ISSUE TITLE
Whether to consider implementing s: Func<TResult> or not.

### ISSUE THREAD

**Issue by wf-soft** [canton7/Stylet#178]
[Async Programming : Patterns for Asynchronous MVVM Applications: Commands](https://docs.microsoft.com/en-us/archive/msdn-magazine/2014/april/async-programming-patterns-for-asynchronous-mvvm-applications-commands)

**Comment by canton7** [comment]
Some more detail would be helpful. You say `Func<TResult>`, but the article talks about making `ICommand.ExecuteAsync` return a `Task`, not a result. Did you mean `Func<Task>`?

**Comment by canton7** [comment]
Closing as no response
