### ISSUE TITLE
Why not use $rootnamespace$ instead of hard code "Company.WpfApplication1" namespace?

### ISSUE THREAD

**Issue by GF-Huang** [canton7/Stylet#179]
![image](https://user-images.githubusercontent.com/4510984/101245879-de342900-374a-11eb-9965-52db6e4ff298.png)

references: https://docs.microsoft.com/en-us/nuget/create-packages/source-and-config-file-transformations

> ```cs
> namespace $rootnamespace$.Models
> {
>     public struct CategoryInfo
>     {
>         public string categoryid;
>         public string description;
>         public string htmlUrl;
>         public string rssUrl;
>         public string title;
>     }
> }
> ```

**Comment by canton7** [comment]
Are you seeing this on the latest version of Stylet.Templates? That should be fixed

**Comment by GF-Huang** [comment]
God, I don't know it has a update. 😢

**Comment by GF-Huang** [comment]
And why not post to https://marketplace.visualstudio.com?

**Comment by canton7** [comment]
Isn't the Visual Studio marketplace just for Visual Studio extensions?

**Comment by GF-Huang** [comment]
Please check [this](https://marketplace.visualstudio.com/search?target=VS&category=Templates&vsVersion=&subCategory=WPF&sortBy=Installs), there are a lot of project templates.

![image](https://user-images.githubusercontent.com/4510984/101249245-29086d80-3758-11eb-9ed0-792afb541485.png)

**Comment by canton7** [comment]
Stylet.Templates is `dotnet new` template, not a Visual Studio template (yes, there is a difference).

You can get `dotnet new` templates to show up in the list of templates in preview versions of Visual Studio, if you enable a preview option somewhere in settings: in the future I assume this will happen by default.

I have no intention of providing a Visual Studio template in addition to the current two templates.

**Comment by GF-Huang** [comment]
OK, thanks.
