### ISSUE TITLE
Missing OnClose/Dispose for inactive items of Conductor<T>.Collection.OneActive

### ISSUE THREAD

**Issue by azabluda** [canton7/Stylet#18]
#14 adds a regression. Methods `OnClose` and `Dispose` are only called for the active item when exiting the `Stylet.Samples.TabNavigation` application in 1.1.18. Both are expected to be called also for inactive items (as it was in 1.1.17).

**Comment by canton7** [comment]
Turns out this was a different issue, which was unmasked in your test case after #14. Pre-1.1.17, you could trigger this by doing 'conductor.Items.Clear()`.

**Comment by canton7** [comment]
Fixed in v1.1.19.
