### ISSUE TITLE
A better way to open a user control from a window?

### ISSUE THREAD

**Issue by chasihle** [canton7/Stylet#182]
Hi,
I have a window form that has a DataGrid. At the bottom of the form I have a contentcontrol which I use to display user controls depending on need.
<ContentControl VerticalContentAlignment="Stretch" HorizontalContentAlignment="Stretch"  s:View.Model="{Binding ActiveItem}" Margin="5,10,5,10"></ContentControl>

I'm opening the the user control in the following manner

```cs
        public void DotheProgAdd()
        {
            if (SelectedProgramType != null)
            {
                CreateCustomerProgramViewModel SubCurrentPage = new CreateCustomerProgramViewModel(SelectedCustomer, STM, SelectedCustomer.CustId, SelectedProgramType.ParmDesc);
                this.ActivateItem(SubCurrentPage);
                LoadComboBoxes();
                LoadProgramGrid();
            }
        }
```

What I want is to have happen is for the DataGrid refreshed following a CRUD operation.

Everything works fine with the exception of the two methods following the this.ActivateItem. When I close the user control with this.RequestClose(), the user control closes but LoadComboBoxes(); and LoadProgramGrid(); are not executed in the initiating window form following the usercontrol close. When I put a breakpoint after the activateitem the flow never brings me back to the first line following the activateitem. 

Is there a better way of  either initiating a user control or closing the usercontrol so that I go back to the intitating method and pickup with the line following the activateitem?

Chanks,
Charlie

**Comment by canton7** [comment]
> I misspoke, the initiating form is a user control not a window
