### ISSUE TITLE
Re# 182

### ISSUE THREAD

**Issue by chasihle** [canton7/Stylet#183]
I misspoke, the initiating form is a user control not a window

**Comment by canton7** [comment]
You can edit your post in the previous issue, or add new comments

**Comment by chasihle** [comment]
So I have  a Window Form I named CustomerConsole has a ContentControl, In customerconsole I select a customer and a usercontrol is opened in the window's contentcontrol, In this case the usercontrol is name CustomerPrograms.. This first usercontrol, CustomerPrograms also has a contentcontrol into which I open a form for CRUD operations depending on the operation. The first user control has a datagrid that i want to refresh when I return from the CRUD operation. The second user control is named CreateCustomerProgram. I put a break point at LoadComboBoxes()  in CustomerPrams which is the first line following  this.ActivateItem(SubCurrentPage); but I never hit the break point. 

I'm wondering if it's because I have a form displaying in a contentcontrol which is also in a content control. so it's like a child contentcontrol

**Comment by canton7** [comment]
I have closed this issue, as it should have been an edit of your previous issue. Please add any further details to [your previous issue](https://github.com/canton7/Stylet/discussions/182)
