### ISSUE TITLE
DoubleAnimation Completed Binding

### ISSUE THREAD

**Issue by pedrollanes** [canton7/Stylet#196]
Is there any way to bind a storyboard completed event?

**Comment by canton7** [comment]
Looks like a normal event: have you tried using an action with it?

(In future, please open questions as discussions. GitHub have removed the helpful button letting me turn issues into discussions however annoyingly)

**Comment by pedrollanes** [comment]
Sorry I will do it in the future.
I tried to use action but I recieved an error.  I think that is an special event and a normal binding action doesn't work

**Comment by canton7** [comment]
What error did you get, exactly?

**Comment by pedrollanes** [comment]
With this code
`  <Trigger Property="Visibility" Value="Visible">
                <Trigger.EnterActions>
                    <BeginStoryboard>
                        <Storyboard>
                            <DoubleAnimation
                                Completed="{s:Action Check}"
                                Storyboard.TargetProperty="Opacity"
                                From="0.0"
                                To="1.0"
                                Duration="0:0:2.5" />
                        </Storyboard>
                    </BeginStoryboard>
                </Trigger.EnterActions>
            </Trigger>
`
and viewmodel action:
`
 public Task Check()
        {
            var a = 0;
            return Task.CompletedTask;
        }
`

Error
Stylet.Xaml.ActionNotSetException: 'View.ActionTarget not set on control System.Windows.Media.Animation.DoubleAnimation (method Check). This probably means the control hasn't inherited it from a parent, e.g. because a ContextMenu or Popup sits in the visual tree. You will need so set 's:View.ActionTarget' explicitly. See the wiki section "Actions" for more details.'

**Comment by canton7** [comment]
I just tried to reproduce this and failed. From Stylet.Samples.Hello, I replaced the `Button` with:

```xaml
<Button Command="{s:Action SayHello}" Content="SayHello" Visibility="{Binding CanSayHello, Converter={x:Static s:BoolToVisibilityConverter.Instance}}">
    <Button.Style>
        <Style TargetType="Button">
            <Style.Triggers>
                <Trigger Property="Visibility" Value="Visible">
                    <Trigger.EnterActions>
                        <BeginStoryboard>
                            <Storyboard>
                                <DoubleAnimation Completed="{s:Action Check}" Storyboard.TargetProperty="Opacity" From="0.0" To="1.0" Duration="0:0:2.5" />
                            </Storyboard>
                        </BeginStoryboard>
                    </Trigger.EnterActions>
                </Trigger>
            </Style.Triggers>
        </Style>
    </Button.Style>
</Button>
```

and add `public void Check() { }` to the VM. The animation works, and `Check` is correctly invoked at the end.

Please could you add a full repro?

**Comment by pedrollanes** [comment]
OK, this afternoon I'll see and I tell you.

**Comment by pedrollanes** [comment]
Ok I have inserted all content into a boton and it works. But if i use in a grid doesn't work. I suppose its right. Thanks

**Comment by canton7** [comment]
Can you post a repro, please? That's not enough information for me to tell what's happening.

**Comment by pedrollanes** [comment]
Ok the problem is that I was putting trigger in a style of a resource dictionary. When I put all the style in the button I have no problem.

**Comment by canton7** [comment]
Ah yeah, it will struggle to find the VM from a ResourceDictionary
