### ISSUE TITLE
Design-Time Binding support for Views

### ISSUE THREAD

**Issue by cH40z-Lord** [canton7/Stylet#2]
In other MVVM frameworks such as MVVM Light, there is a ViewModelLocator class which is used to retrieve the ViewModels (View First) which allows you to specify the type of the DataContext to get design time support for all of your bindings.
So far I haven't been able to find such feature in the docs. Is anything like that planned?

**Comment by canton7** [comment]
Righty, there's a full example at https://github.com/canton7/Stylet/compare/develop...feature/design-time

What do you think @cH40z-Lord ? If that looks vaguely like what you were expecting, I'll write some docs.

**Comment by cH40z-Lord** [comment]
I've cloned the code locally and had a brief look at the Sample project. So far everything looks nice and complete :) Couldn't think of anything that didn't work or was hard to implement.

To wrap this up I'd say that you did a very good job implementing everything. Very well done - thank you! This is definitely a time saver.

**Comment by canton7** [comment]
Sweet! Thanks for the prodding.

I need to get a bit more stuff into the base library in order to get the test coverage for the design-time branch up, then there's docs to write... Hopefully I'll get this merged in a week or so.
