### ISSUE TITLE
ViewModels collection for Conductor<IScreen>.Collection.OneActive

### ISSUE THREAD

**Issue by Splinterjke** [canton7/Stylet#21]
Is there any the fastest way to set overrided IModelValidator for all ViewModels and add all ViewModels in some ShellViewModel not like this default way:
```cs
public MainViewModel(SomeViewModel tab1, AnotherViewModel tab2, /*etc*/) { //Adding items }
```
and not with (for every usercontrol viewmodel):
```cs
public SomeViewModel(IModelValidator<SomeViewModel> validator) : base(validator) { //smthg }
```
I mean the situation when there is alot of UserControls in Project.

**Comment by Splinterjke** [comment]
Got it from Caliburn.Micro like this:
Main ViewModel
```cs
public class MainViewModel : Conductor<IScreen>.Collection.OneActive
{
    public MainViewModel(IEnumerable<TabItem> tabs)
    {
        DisplayName = "Name";						
        Items.AddRange(tabs);
    }
}
```
Prepared a marker interface for all child items
```cs
public interface TabItem: IScreen
{
}
```
Registering and binding interface to viewmodels
```cs
protected override void ConfigureIoC(IStyletIoCBuilder builder)
{
     builder.Bind(typeof(TabItem)).ToAllImplementations();
}
```

**Comment by canton7** [comment]
Hi,

Sorry for the delay - Christmas and New Year happened.

Is your question resolved?

Note that, in your second post, the order of `tabs` isn't guaranteed: it may changed based on random stuff.

**Comment by Splinterjke** [comment]
You're absolutely right, the tabs will be placed in the same order the classes are injected, but I have custom sorting for that. If someone wants to have a control over the ordering, you can order them in 'MainViewModel' constructor by either passing a custom 'IComparer<ITabItem>' or adding some property you can OrderBy or select to the ITabItem interface. Also you can use IList methods to sort items. The default selected item will be the first one in the Items list (the same as in caliburn.micro tho). Question is resolved ofc.
