### ISSUE TITLE
Stylet.StyletInvalidViewTypeException

### ISSUE THREAD

**Issue by Splinterjke** [canton7/Stylet#22]
Hello. I get this exception says that View doesn't derive from the Window class. But I call .ShowDialog from Conductor<IScreen>.Collection.OneActive derives from Window.
Window's ViewModel:
```
public class MainViewModel : Conductor<IScreen>.Collection.OneActive
    {
        private ErrorBoxViewModel errorBox;
        private readonly IWindowManager windowManager;

        public MainViewModel(IWindowManager windowManager)
        {
            this.windowManager = windowManager;
        }

        public void ShowError(string message)
        {
            if (errorBox != null)
                errorBox.RequestClose();
            errorBox = new ErrorBoxViewModel(message);
            this.windowManager.ShowDialog(errorBox);
        }
    }
```
In another view model derives from UserControl I call:
`(Conductor as MainViewModel).ShowError("some string");`

ErrorBoxViewModel view model derives from UserControl as well:
```
public class ErrorBoxViewModel : Screen
    {
        public string Message { get; private set; }

        public ErrorBoxViewModel(string message)
        {
            this.Message = message;
        }

        protected override void OnActivate()
        {
            base.OnActivate();
        }

        protected override void OnDeactivate()
        {
            base.OnDeactivate();
        }

        public void CloseWithSuccess()
        {
            this.RequestClose(true);
        }
    }
```

Any Idea what's wrong?

**Comment by canton7** [comment]
`ErrorBoxView` doesn't derive from `Window`.

When you call `ShowWindow(someViewModel)`, the view for `someViewModel` must inherit from `Window` (otherwise it can't be shown as a Window).

**Comment by Splinterjke** [comment]
Well, than how to add custom usercontrol to MainViewModel from Conductor or ActiveItem of Conductor?

**Comment by canton7** [comment]
I'm afraid I don't understand the question.,

**Comment by Splinterjke** [comment]
I have a custom usercontrol that I want to display over ActiveItem of Conductor. I'm looking for a way to dynamically create the usercontrol from all of Conductor items?

**Comment by canton7** [comment]
What do you mean, "display over ActiveItem of Conductor"? What does "over" mean, exactly?

What do you mean by "dynamically create the usercontrol from all Conductor items"? What UserControl? How do you create a UserControl "dynamically"?

**Comment by Splinterjke** [comment]
Okay, forget about dynamic. I have a Conductor (Window) and an ActiveItem (UserControl) as TabItem. I wan't to display another 'custom usercontrol' on Window. I guess I can add ths 'custom control'to mainview xaml and change the visibility from ActiveItem, but there is an Message property in ctor of 'customcontrol' that i want to change as well.

**Comment by canton7** [comment]
> I wan't to display another 'custom usercontrol' on Window

What do you mean, "on Window"? Do you mean display it as a new Window? Do you mean display it in the MainView, but on top of the TabControl? Something else?

**Comment by Splinterjke** [comment]
Yes, displaying as UsetControl but on top of the TabControl.

**Comment by canton7** [comment]
So not as a Window at all?

You'll want to put both the TabControl and the overlay in the same Grid, so that the overlay is placed on top of the TabControl. Something like this (untested, might have errors):

```xaml
<Window x:Class="Your.MainView ....>
    <Grid>
        <!-- Display both the overlay and the TabControl, with the overlay on top of the TabControl -->
        <TabControl .....>
        </TabControl>
        <ContentControl s:View.Model="{Binding Overlay}"/>
    </Grid>
</Window>
```

```csharp
public class MainViewModel : Conductor<IScreen>.Collection.OneActive
{
    private IScreen _overlay;
    public IScreen Overlay
    {
        get { return this._overlay; }
        private set { this.SetAndNotify(ref this._overlay, value); }
    }

    public void ShowOverlay()
    {    
        this.Overlay = new SomeViewModel();
    }
}

**Comment by Splinterjke** [comment]
Thank you. That's exactly what I want. Issue is resolved.

**Comment by canton7** [comment]
Cool!
