### ISSUE TITLE
Does Stylet have a something like a EventArgsConverter equivalent?

### ISSUE THREAD

**Issue by FutureTD** [canton7/Stylet#25]
First I would like to say excellent library and to keep up the good work!

As for my question, I am currently using a few third party controls from DevExpress, and a few of the controls pass information through the eventargs.  I was wondering if there was a way using Stylet to pass eventargs to the ViewModel or better yet a converter that could convert the eventargs to the type I need.

The DevExpress MVVM framework handles it like this:

```
 <dxmvvm:Interaction.Triggers>
      <dxmvvm:EventToCommand Command="{Binding YOURCOMMAND}"
                            EventName="THEEVENT"
                            EventArgsConverter="{StaticResource YOUREVENTARGSCONVERTER}"
                            PassEventArgsToCommand="true" />
</dxmvvm:Interaction.Triggers>
```

Caliburn Micro has:

`cm:Message.Attach="[Event LeftSwipe] = [LeftSwipe($source, $eventArgs)]"`

In which the $eventArgs are passed to the method on your ViewModel, or you can even create your own $keyword to convert the eventargs to another object (Which I would prefer because I do not want to pass eventargs directly to my ViewModel).

I was just wondering if Stylet had a equivalent?

**Comment by RyanYANG52** [comment]
Did you read this wiki [https://github.com/canton7/Stylet/wiki/Actions](url)  :section Events,  is this what you looking for?

`
   <Button Click="{s:Action DoSomething}">Click me</Button>
`

I do not think there is an existed eventarg converter, you should wait see what canton7 have to say

**Comment by canton7** [comment]
Yep, @RyanYANG52 is spot on. When you use an action with an event, you can grab the source and the event args in a very similar way to your Caliburn.Micro example (but without the ability to convert the EventArgs to another object). There's no concept of an EventArgsConverter.

**Comment by FutureTD** [comment]
thanks, that should work
