### ISSUE TITLE
Unable to validate properties of class within viewmodel

### ISSUE THREAD

**Issue by FolkCoder** [canton7/Stylet#26]
I am simply not able to figure out how to use ValidatingModelBase to validate properties of a class within a viewmodel. As a quick test, I modified the Stylet ModelValidation sample to organize the existing properties under a new User class.

```csharp
using FluentValidation;

namespace Stylet.Samples.ModelValidation.Pages
{
    public class User
    {
        public string UserName { get; set; }
        public string Email { get; set; }
        public Stringable<int> Age { get; set; }
    }

    public class UserViewModel : Screen
    {
        private IWindowManager windowManager;

        public UserViewModel(IWindowManager windowManager, IModelValidator<UserViewModel> validator) : base(validator)
        {
            this.AutoValidate = false;
            this.windowManager = windowManager;
            this.User = new User();
        }

        public User User { get; set; }

        public void Submit()
        {
            if (this.Validate())
            {
                this.windowManager.ShowMessageBox("Successfully submitted", "success");
            }                
        }        
    }

    public class UserViewModelValidator : AbstractValidator<UserViewModel>
    {
        public UserViewModelValidator()
        {
            RuleFor(x => x.User).SetValidator(new UserValidator());
        }
    }

    public class UserValidator : AbstractValidator<User>
    {
        public UserValidator()
        {
            RuleFor(x => x.UserName).NotEmpty().Length(1, 20);
            RuleFor(x => x.Email).NotEmpty().EmailAddress();
            RuleFor(x => x.Age).Must(x => x.IsValid).WithMessage("{PropertyName} must be a valid number");
            When(x => x.Age.IsValid, () =>
            {
                RuleFor(x => x.Age.Value).GreaterThan(0).WithName("Age");
            });
        }
    }
}
```

I had to change the databindings in UserView; I tried to bind using the full path as well as by setting a DataContext.

```xaml
        <Label Grid.Row="0" Grid.Column="0" Target="{Binding ElementName=UserName}">UserName:</Label>
        <TextBox DataContext="{Binding User}" Grid.Row="0" Grid.Column="1" x:Name="UserName" Text="{Binding UserName, UpdateSourceTrigger=PropertyChanged}"/>

        <Label Grid.Row="1" Grid.Column="0" Target="{Binding ElementName=Email}">Email:</Label>
        <TextBox Grid.Row="1" Grid.Column="1" x:Name="Email" Text="{Binding User.Email, UpdateSourceTrigger=PropertyChanged}"/>

        <Label Grid.Row="2" Grid.Column="0" Target="{Binding ElementName=Age}">Age:</Label>
        <TextBox Grid.Row="2" Grid.Column="1" x:Name="Age" Text="{Binding User.Age, UpdateSourceTrigger=PropertyChanged}"/>
```

It's obvious that the validations are actually working in the viewmodel, as the Success message is only thrown when the form is filled out correctly. However, I simply can't figure out to force the failed validations to trigger the error templates in the view.

Any ideas?

**Comment by RyanYANG52** [comment]
Textbox Error template wasn't be triggered is because `User` class is not based on `ValidatingModelBase` , so the property of User changed will not trigger `INotifyDataErrorInfo`.

One way you can do this is like this:
```
    public class UserViewModel:Screen
    {
        private User _user;
        public User User { get => _user; set => _user = value; }
        public UserViewModel(IModelValidator<UserViewModel> validator,Func<User> userFactory) : base(validator)
        {
            this.User = userFactory();
        }        
    }

    public class UserViewModelValidator : AbstractValidator<UserViewModel>
    {
        public UserViewModelValidator()
        {
            RuleFor(x => x.User).Must(user => !user.HasErrors);
        }
    }

    public class User:ValidatingModelBase
    {
        private string _name;

        public string Name { get => _name; set => SetAndNotify(ref _name, value); }

        public User(IModelValidator<User> validator) : base(validator)
        {
            this.Validate();
        }
    }

    public class UserValidator : AbstractValidator<User>
    {
        public UserValidator()
        {
            RuleFor(x => x.Name).NotEmpty().Length(1, 20);
        }
    }

```
The other way(untested): maybe you can do something like this directly:

```
        public UserViewModelValidator()
        {
            RuleFor(x=>x.User.Name).NotEmpty().Length(1, 20);
        }
```

**Comment by canton7** [comment]
Thanks @RyanYANG52!

Yeah, WPF will only validate properties on classes which implement `INotifyDataErrorInfo`, as `ValidatingModelBase` does (or which implement the older `IDataErrorInfo`). It's similar to INPC: you can only raise PropertyChanged events for properties on classes which implement `INotifyPropertyChanged`.

In general, you should not bind to something which isn't a ViewModel in MVVM. This is one of the reasons why: the class being bound to often needs to implement INPC or `INotifyDataErrorInfo`.

**Comment by FolkCoder** [comment]
Thank you both for the clarifications, this definitely points me in the right direction!

I'm so used to Fody.PropertyChanged automatically injecting INPC notification in my viewmodels that I didn't even think about adding INotifyDataErrorInfo to my model. Any chance of Stylet implementing something like Fody.Validar to achieve this?

**Comment by canton7** [comment]
@FolkCoder If you're using PropertyChanged.Fody, your ViewModels still need to implement INotifyPropertyChanged (or you need to decorate them with `[ImplementPropertyChanged]`, but that has some downsides). The easiest way to do this is by deriving from `PropertyChangedBase` or one of its subclasses.

You shouldn't need to implement `INotifyDataErrorInfo` explicitly in your ViewModels - derive from `ValidatingModelBase`, which implements `INotifyDataErrorInfo` for you (that's the point of that class). `ValidatingModelBase` uses the INPC mechanisms to raise validation errors automatically: whenever a property changes (as detected by the INPC mechanism, including PropertyChanged.Fody), `ValidatingModelBase` will validate that property and raise any errors. This is all explained in [the wiki](https://github.com/canton7/Stylet/wiki/ValidatingModelBase).

**Comment by canton7** [comment]
Closing as the discussion seems to have reached a conclusion.
