### ISSUE TITLE
OnInitialActivate get called when closing application.

### ISSUE THREAD

**Issue by wakuflair** [canton7/Stylet#27]
This can be reproduced with `Stylet.Samples.RedditBrowser` sample:

1. Put a breakpoint at [This line](https://github.com/canton7/Stylet/blob/master/Samples/Stylet.Samples.RedditBrowser/Pages/SubredditViewModel.cs#L24)
1. Launch the sample.
1. Open a tab, the breakpoint will be triggered.
1. Close the sample application, the breakpoint will be triggered again.

**Comment by canton7** [comment]
Thanks! I'll release this fix shortly.
