### ISSUE TITLE
Dispose get called twice.

### ISSUE THREAD

**Issue by wakuflair** [canton7/Stylet#28]
Hi, I encoutered another problem with closing.

This also can be reproduced with `Stylet.Samples.RedditBrowser` sample, but need a bit of change:

1. Add `IDisposable` to the `SubredditViewModel` class.
2. Implement the `Dispose` method with any content.
3. Put a breakpoint inside the `Dispose` method.
4. Launch the sample application.
5. Open a tab, then click the `Close` button.
6. The breakpoint will be triggered twice.

**Comment by canton7** [comment]
Thanks for spotting this.

*Technically* this isn't an issue - the Microsoft guidelines are that Dispose methods may be called multiple times, and Dispose implementations should be resilient to this. That said, it's a bit ugly, so I'll try and fix.

**Comment by canton7** [comment]
I'll give it another day or two in case you spot something else, then push a new release.
