### ISSUE TITLE
Style.Start should generate files with a BOM

### ISSUE THREAD

**Issue by wakuflair** [canton7/Stylet#30]
If ShellView.xaml contains non-ascii characters(e.g. Chinese), build error will occure.

**Comment by canton7** [comment]
It does use UTF-8, [see here](https://github.com/canton7/Stylet/blob/d0f814e69910b8fd424f8ad4b78015368200e113/NuGet/start/tools/install.ps1#L278).

**Comment by wakuflair** [comment]
WriteAllText used UTF-8 without BOM, and since the default content of the ShellView.xaml only contains ascii characters, so UTF-8(no bom)is the same with system default encoding(it's GB2312 in Chinese OS). Then if any chinese is typed in, the xaml compiling failed.

Adding Encoding.UTF8 as the 3rd parameter to the WriteAllText method should fix this issue.

**Comment by canton7** [comment]
> so UTF-8(no bom)is the same with system default encoding(it's GB2312 in Chinese OS)

That seems unlikely. UTF-8 means UTF-8. It doesn't mean "the system's encoding".

**Comment by wakuflair** [comment]
Reproduce steps:

1. Create a new WPF project.
1. Add Stylet.Start nuget package.
1. Open ShellView.xaml, Change "Hello Stylet!" at Line 12 to "你好".
1. Build the solution you can see the error.

Visual Studio 2015 Enterprise with Update3.
Win10 Professional x64.

**Comment by canton7** [comment]
I see this dialog, and if I click "yes", everything works as expected.

![encoding](https://cloud.githubusercontent.com/assets/568104/26778024/6423d8ea-49d7-11e7-9e2c-0cb4a284a089.png)

My guess is that Visual Studio interprets the file in some default encoding since it doesn't contain a BOM. Chinese characters aren't part of that encoding, so it offers to save the file as Unicode. Saving the file with a BOM should indeed fix that issue, but not for the reason you said.

**Comment by wakuflair** [comment]
The error is 'Invalid character in the given encoding. Line 12, position 9.' XML is not valid.

**Comment by wakuflair** [comment]
I think the dialog will only appear when your OS is not Chinese OS. On my OS , VS directly saved the file with GB2312 encoding.

**Comment by canton7** [comment]
GB2312 is capable of displaying Chinese characters though? So you shouldn't see an encoding error.

**Comment by canton7** [comment]
Changed it to UTF-16 with BOM, anyway, which is what VS uses.

**Comment by canton7** [comment]
Reopening until I release this
