### ISSUE TITLE
Cannot open a new discussion!

### ISSUE THREAD

**Issue by SwaroopSomanna** [canton7/Stylet#305]
**Description**
I'm using GitHub app on Android.
I want to ask a question and unable to open a new discussion as clicking on Open a Discussion takes me to a 404 error page.

**Comment by canton7** [comment]
Works for me: it a should take you here? https://github.com/canton7/stylet/discussions/new

You can also click the discussions tab at the top of the page

**Comment by SwaroopSomanna** [comment]
> Works for me: it a should take you here? https://github.com/canton7/stylet/discussions/new
> 
> You can also click the discussions tab at the top of the page 

Ok I hadn't signed in to GitHub on my browser and that's what was causing the error. Now that I've signed-in its working.

**Comment by canton7** [comment]
Aha nice find. I don't think there's anything I can do about that I'm afraid
