### ISSUE TITLE
Binding Windows's Left and Top property doesn't work.

### ISSUE THREAD

**Issue by wakuflair** [canton7/Stylet#31]
Hi.

I binded a Window's Left and Top properties to a ViewModel, and set `        WindowStartupLocation="Manual"`.
However it's doesn't work.

I debugged into [this](https://github.com/canton7/Stylet/blob/50d58b7291ae690af5f12aaa824c521dc4c5e4b8/Stylet/WindowManager.cs#L191) line , and notice that because I binded the Left and Top, their values are always `Double.NaN`, so WindowManager always set its startup location to center.

**Comment by canton7** [comment]
Replicated, thanks!

**Comment by canton7** [comment]
Note to self: check for bindings on the Top and Left properties using `BindingOperations.GetBinding`.

**Comment by canton7** [comment]
Fixed in 1.1.21.
