### ISSUE TITLE
View not updated when property of item in ObservableCollection changes

### ISSUE THREAD

**Issue by hmihail** [canton7/Stylet#33]
I have a `IObservableCollection` which holds a collection of items like this:

    public IObservableCollection<ProductGroup> ProductGroups { get; private set; }

When I edit one item in another view, by sending the `SelectedProductGroup` item to it, when I return in the parent view the DataGrid is not updated, even if the item comes back updated.

Any ideas what I am doing wrong?

**Comment by KnightSpirit** [comment]
@hmihail 
I think you should confirm 
`class ProductGroup`
extends PropertyChangedBase

**Comment by canton7** [comment]
Each `ProductGroup` needs to implement INPC, and the PropertyChanged event needs to be raised whenever properties on `ProductGroup` are changed.

I'm not sure what you mean by "by sending the SelectedProductGroup item to it" or "when I return in the parent view the DataGrid is not updated". What is SelectedProductGroup, and how do you send it? Where did the DataGrid come from? How do you return in a view?

**Comment by hmihail** [comment]
No, it does not.

**Comment by canton7** [comment]
Not sure what you're referring to.

I'm fairly sure this is not a Stylet issue, but is instead a general MVVM question. I'm happy to help to a degree, but in return you need to use things like complete sentences which give me the information I ask for.

**Comment by hmihail** [comment]
I think my English wasn't at its best. Here is the missing code:

        public ProductGroupsViewModel(IWindowManager windowManager)
        {
            this.windowManager = windowManager;

            ProductGroups = new BindableCollection<ProductGroup>();

            persistenceService = ServiceRepository.GetService<EntityPersistenceService>(EntityPersistenceService.ID);

            var productGroupsList = persistenceService.GetAll<ProductGroup>();
            ProductGroups.AddRange(productGroupsList);
        }

        private ProductGroup _selectedProductGroup;
        public ProductGroup SelectedProductGroup
        {
            get { return _selectedProductGroup; }
            set
            {
                _selectedProductGroup = value;
                SetAndNotify(ref _selectedProductGroup, value);
            }
        }

        public void EditItem()
        {
            if (SelectedProductGroup == null) return;

            var productGroupViewModel = new ProductGroupViewModel(SelectedProductGroup);
            bool? result = windowManager.ShowDialog(productGroupViewModel);

            if (!result.GetValueOrDefault(true)) return;

            persistenceService.Save(SelectedProductGroup);
        }

**Comment by hmihail** [comment]
@canton7, I am sure is not related to Stylet, but I was searching for an answer all day, and found no solution.
In the examples in Stylet master repository, you have a Master-Detail example which is working, and the model does not implement INPC

**Comment by canton7** [comment]
Thanks for the code. Does the SelectedProductGroup VM implement INPC?

**Comment by canton7** [comment]
So you give a ProductGroup (not a VM) to a new ProductGroupViewModel. The ProductGroupViewModel mutates the ProductGroup, and you expect the ProductGroupsViewModel to show the changes to that ProductGroup?

There's no way for WPF to know that you've changed the ProductGroup, because you never tell it, and because ProductGroup is a model which doesn't implement INPC.

Either restructure things so that SelectedProductGroup is a VM which implements INPC, and so WPF knows when it has changed (preferable), or explicitly tell WPF that the SelectedProductGroup property has changed by calling `NotifyOfPropertyChange(nameof(SelectedProductGroup))`

**Comment by hmihail** [comment]
Thanks! 

So in the first approach I should bind the `DataGrid` to a `IObservableCollection<ProductGroupViewModel>`? In that case I will need to contruct it myself after I retrieve it from the data service, right? 

I was thou intrigued that in the example from the Github repo, your model does not implement INPC but sill works.

**Comment by hmihail** [comment]
Why is this example from Stylet repo working without Model implementing INPC?

    public class ShellViewModel : Screen
    {
        public IObservableCollection<EmployeeModel> Employees { get; private set; }

        private EmployeeModel _selectedEmployee;
        public EmployeeModel SelectedEmployee
        {
            get { return this._selectedEmployee; }
            set { SetAndNotify(ref this._selectedEmployee, value) ;}
        }
    }

    public class EmployeeModel
    {
        public string Name { get; set; }
    }

I don't understand.

**Comment by canton7** [comment]
To be honest, I'm not sure. I think WPF must be doing some magic, since it shouldn't work... I might just update the sample.
