### ISSUE TITLE
WindowManager.ShowMessageBox is not showing custom View

### ISSUE THREAD

**Issue by FutureTD** [canton7/Stylet#34]
I have created a custom MessageBoxViewModel that is implementing IMessageBoxViewModel along with a custom view, MsgBoxViewModel and MsgBoxView respectively. I have set my IoC container (AutoFacBootstrapper) as follows.

builder.RegisterType<MsgBoxViewModel>().As<IMessageBoxViewModel>().ExternallyOwned();

However, when I call 

_windowManager.ShowMessageBox("test", "test");

It shows up, but not using the view I custom styled. Seems like its using some default view.

**Comment by canton7** [comment]
Hmm, looks like I broke that a few years ago... https://github.com/canton7/Stylet/blob/master/Stylet/WindowManager.cs#L130

**Comment by canton7** [comment]
You can grab an intermediate build from the NuGet feed https://ci.appveyor.com/nuget/stylet

**Comment by FutureTD** [comment]
Was this update pushed to the newest version? I even tried to update using the original link above and I still seems to bu using the default view.

**Comment by canton7** [comment]
No, I haven't yet released this (I should do, thanks for the reminder) but the intermediate version 1.1.21.130 from the nuget feed above should work.

Someone submitted a PR based on master which triggered some builds with newer version numbers than 1.1.21.130, which is probably what you're installing.

**Comment by FutureTD** [comment]
Checking in again, could this fix be pushed to the latest version?

**Comment by canton7** [comment]
Sorry for the delay, released!
