### ISSUE TITLE
WindowManager.ShowWindow: How to set window's owner?

### ISSUE THREAD

**Issue by wakuflair** [canton7/Stylet#36]
I have a ViewModel which shows some popup windows using `WindowManager.ShowWindow`.
The showing is fine, however when I press ALT+TAB I can see all the popup windows in the window list.

I googled and found that I need to set the showing windows' owner, but the WindowManager seems can not do it.
For now I used an inelegant way: after calling ShowWindow, I published an event through EventAggregator to the owner's view and pass the popup viewmodel as a parameter, and in the view's codebehind, set its owner: `((Window) message.ViewModel.View).Owner = this;`.

Yes, I don't like it :(

**Comment by canton7** [comment]
It gets set for dialogs: https://github.com/canton7/Stylet/blob/3b64396f5fa5c90b4a59262585416a723435a949/Stylet/WindowManager.cs#L164. There's currently no easy way to set it for windows which are not dialogs, as you observed.

You could do something like:

```csharp
var vm = new WhateverViewModel();
viewManager.CreateAndBindViewForModel(vm);
((Window)vm.View).Owner = (Window)this.View;
this.windowManager.ShowWindow(vm);
```

Or you could subclass the WindowManager to add a ShowWindow overload which takes an `IViewAware` owner property and does much the same thing.
