### ISSUE TITLE
I have a class ScreenEx that inherits from Screen, rewriting OnActivate in a new ViewModel that is unresponsive

### ISSUE THREAD

**Issue by kuangxj** [canton7/Stylet#385]
**Description**
I have a class ScreenEx that inherits from Screen, rewriting OnActivate in a new ViewModel that is unresponsive

**To Reproduce**
```cs
class ScreenEx : Screen
{
    public string ContentId { get; set; } = Guid.NewGuid().ToString();
}

class TestViewModel:ScreenEx,IDisposable
{
  
    protected override void OnActivate()
    {
        // After F9 ,not work.
        base.OnActivate();
    }
    public void Dispose()
    {
        
    }
}
```

**Version Info**
 - Stylet version: [e.g. 1.2.3]
 - Runtime version: [e.g. 5.0.300]

**Additional Info**

**Comment by canton7** [comment]
I tried to reproduce the problem using your code, but it worked fine.

**Comment by kuangxj** [comment]
I replied after trying.

**Comment by canton7** [comment]
I'm not sure what you mean by that

**Comment by kuangxj** [comment]
I fix it,thanks.
