### ISSUE TITLE
Chinese garbled characters

### ISSUE THREAD

**Issue by Ann520** [canton7/Stylet#392]
In XAML documents, different writing styles will display different content

![屏幕截图 2024-06-17 153037](https://github.com/canton7/Stylet/assets/38491249/c2627f2e-3413-4a7b-b57b-caaff7f0d3d4)
As shown in the figure, the second content displays an error and is not in Chinese

**Comment by canton7** [comment]
I don't think this is anything to do with Stylet? I suspect you will have the same issue in a plain WPF project without Stylet.

**Comment by Ann520** [comment]
抱歉，我刚刚在项目里把stylet删了，又显示正常了，如图所示，我的stylet版本是1.3.4，.NET4.5.2

I hope you can try multiple times
The code is as follows:&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; <Label
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Grid.Row="7"
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Grid.Column="0"
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Content="直门" /&gt;
&nbsp; &nbsp; &nbsp; &nbsp; <TextBox
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Grid.Row="7"
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Grid.Column="1"
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Text="直门-_" /&gt;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Antony ***@***.***&gt;; 
发送时间: 2024年6月17日(星期一) 下午3:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [canton7/Stylet] Chinese garbled characters (Issue #392)














 
I don't think this is anything to do with Style? I suspect you will have the same issue in a plain WPF project without Stylet.

**Comment by canton7** [comment]
Stylet does not do anything which might affect how a Label or TextBox works. I can't see how this can possibly be a problem with Stylet.

**Comment by Ann520** [comment]
抱歉，我已经找到原因了，是metro引用资源文件的原因，感谢你的耐心回答~




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Antony ***@***.***&gt;; 
发送时间: 2024年6月17日(星期一) 下午4:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [canton7/Stylet] Chinese garbled characters (Issue #392)














 
Stylet does not do anything which might affect how a Label or TextBox works. I can't see how this can possibly be a problem with Stylet.

**Comment by canton7** [comment]
I'm glad you fixed it!
