### ISSUE TITLE
Injected type is null in ViewModel

### ISSUE THREAD

**Issue by hmihail** [canton7/Stylet#40]
I need a repository injected in my ViewModel, but it comes null. Here is what I do:

in Bootstrapper:

```
protected override void ConfigureIoC(IStyletIoCBuilder builder)
{
    builder.Bind<IProductGroupRepository>().ToInstance(new ProductGroupRepository(dbConn));
}
```
and in my ViewModel:

```
[Inject]
private IProductGroupRepository productGroupRepository;
```

but it comes null.
Am I doing something wrong?
Thanks!

**Comment by canton7** [comment]
How are you constructing the ViewModel? When do you check whether the 'productGroupRepository' field is null?

**Comment by hmihail** [comment]
When I want to use the injected type in my ViewModel I get a null pointer exception. I just switched to constructor injection and that works. Only property injection doesn't.

**Comment by canton7** [comment]
Please answer my questions.

> How are you constructing the ViewModel? 

Show me the code where you get a new instance of the ViewModel.

> When do you check whether the 'productGroupRepository' field is null?

When do you "use the injected type"? Is it in the constructor? Is it in another method? Show me the code.

**Comment by hmihail** [comment]
Here is the constructor of the ViewModel:

```
[Inject]
private IProductGroupRepository productGroupRepository;

public ProductGroupsViewModel(IWindowManager windowManager)
{
    this.windowManager = windowManager;

    ProductGroups = new BindableCollection<ProductGroup>();

    var productGroups= productGroupRepository.GetAll();
    ProductGroups.AddRange(productGroups);
}
```

**Comment by canton7** [comment]
> Show me the code where you get a new instance of the ViewModel.

**Comment by hmihail** [comment]
Here it is:

```
var productGroupsViewModel = new ProductGroupsViewModel(windowManager);
windowManager.ShowDialog(productGroupsViewModel);
```

**Comment by canton7** [comment]
In code sample, you try and use the productGroupRepository in the constructor. Of course the field is going to be null in the constructor: the IoC container has to call the constructor to create a new instance of the type before it sets any of the values of the fields. Therefore it can't set the productGroupRepository field until after the constructor has finished running. 

This is spelled out [in the documentation](https://github.com/canton7/Stylet/wiki/StyletIoC-Injection):

> Because the properties are injected after the type is constructed, everything which happens in the constructor must not rely on these properties being populated. This is another reason to prefer constructor injection. If you do need to know when the properties are injected, implement the interface IInjectionAware. The interface method PropertiesInjected will be called when all properties have been injected.

Of course, that only applies if the IoC container creates the ViewModel instance.

In your second code sample, you're not even using the IoC container to create your ProductGroupsViewModel instance at all! You're creating it yourself. Therefore there's no possible way for the IoC container to inject anything, as it's not involved in the construction of the type at all!

**Comment by hmihail** [comment]
I only need the repository injected, not the ViewModel, which I create myself, I'm OK with that. I wanted to use the [Inject] attribute instead of contructor injection because I have a chain of 3-4 windows, and I will have to inject the repository all the way up to ShellViewModel, even if I only need it in the last window open.

**Comment by canton7** [comment]
If you create the ViewModel yourself, nothing is going to get injected. You cannot use the IoC container to inject anything if you create the ViewModel yourself (unless you call `BuildUp`, see the documentation I linked to above).

The best thing to do is **not** to create the ViewModel instance yourself. Instead, inject the ViewModel (or a `Func<ViewModel>`) into the page which needs it.

**Comment by hmihail** [comment]
My ShellViewModel is a window with a lot of buttons, each opening another window. I will probably need a ViewModelFactory injected, then use this factory to construct all my ViewModels need?

**Comment by canton7** [comment]
I tend to just inject a lot of Funcs, but you can inject a factory if you'd rather.

**Comment by canton7** [comment]
Closing as there's no issue.

**Comment by hmihail** [comment]
I managed to create an abstract factory to handle injection, and it works. Now I have another problem which I don't know hot to solve. In one VM I need a runtime object injected, and I have't found a way to do it. I need a constructor like this:

```
public ProductViewModel(Product product, 
            IWindowManager windowManager, 
            IViewModelFactory viewModelFactory)
{
    this.product = product;
}
```
I call the VM like this:

```
var product = ProductRepository.Get(1);
var viewModel = viewModelFactory.CreateProductViewModel();
bool? result = windowManager.ShowDialog(viewModel);
```


Any way to achieve this?
Thanks!

**Comment by canton7** [comment]
Either make the `Product` a property of the `ProductViewModel` (not a ctor parameter), or write your own factory:

```csharp
public class ProductViewModelFactory
{
    private readonly ISomeDependency someDependency

    public ProductViewModelFactory(ISomeDependency someDependency)
    {
        this.someDependency = someDependency;
    }

    public ProductViewModel CreateProductViewModel(Product product) => new ProductViewModel(this.someDependency, product);
}
```

**Comment by hmihail** [comment]
Thanks! It worked.
