### ISSUE TITLE
Conducting the RootViewModel

### ISSUE THREAD

**Issue by MeikTranel** [canton7/Stylet#41]
I'm trying to isolate a splash screen, login windows and the main application host window into separate windows. My problem is that it seems to look like it was never intended to switch the root viewmodel and thus its window. Or am i missing something?

**Comment by canton7** [comment]
I'm afraid I'm not quite clear on what you're trying to do. Do you want to display three windows on startup? Show extra windows at various points during the application's lifetime? Change the content of a single window?

**Comment by MeikTranel** [comment]
What i'm trying to do is this:

- Open the Application via Bootstrapper
- Bootstrappers RootViewmodel is a ViewModel without a Window
- the ViewModel itself bootstraps to different window view / viewmodel combinations
- the first would be a LoginViewModel / LoginView[Window] 
- after login succeeded the loginview requests the rootviewmodel to change the active window to the splash screen viewmodel / view[window]
- after splash screen loading has finished it requests the rootviewmodel to open the mainviewmodel/mainview

**Comment by canton7** [comment]
In your bootstrapper:

```csharp
protected override void DisplayRootView(object rootViewModel)
{
    // Don't show anything
}
```

Then the bootstrapper won't try and show anything, and it's up to you to show your first window.

**Comment by canton7** [comment]
Closing as resolved. Please re-open if this is still an issue.
