### ISSUE TITLE
Bind and invoke

### ISSUE THREAD

**Issue by ThomasBarnekow** [canton7/Stylet#43]
Firstly, let me say that this is more of a question or possibly suggested feature than an issue.

Looking at your `Bind` or `BindWeak` extension methods, would it make sense to add something like `BindAndInvoke` or `BindWeakAndInvoke`, which would not only bind but also invoke the handler once, e.g., to be able to also initialize dependent properties, for example, in one go?

Here is a quick-and-dirty example of what I mean:
```
        public static IEventBinding BindAndInvoke<TSource, TProperty>(
            this TSource target,
            Expression<Func<TSource, TProperty>> targetSelector,
            EventHandler<PropertyChangedExtendedEventArgs<TProperty>> handler) where TSource : class, INotifyPropertyChanged
        {
            IEventBinding listener = Bind(target, targetSelector, handler);

            string propertyName = targetSelector.NameForProperty();
            Func<TSource, TProperty> propertyAccess = targetSelector.Compile();
            handler(target, new PropertyChangedExtendedEventArgs<TProperty>(propertyName, propertyAccess(target)));

            return listener;
        }
```
I'm not sure about the best order (e.g., bind first and then invoke once or the other way around). But the idea is to avoid duplication of code, e.g., if you have to essentially repeat what would be done by the handler in addition to establishing the binding.

**Comment by canton7** [comment]
I'm kind of inclined to say that this, although valid, is probably fairly niche, and I've tried to avoid adding things to the framework unless there's a pretty compelling reason. I'll have a think, though.

**Comment by ThomasBarnekow** [comment]
@canton7 Thanks.

In my use case, a view model aggregates services, some of which are initialized asynchronously. A few service properties are passed through to the view via the view model, which thus acts as a facade. Binding and initializing the dependent properties in one go would be kind of elegant.

**Comment by canton7** [comment]
Sorry this took quite so long...
