### ISSUE TITLE
In XAML, Resharper/VS complains that ApplicationLoader needs a key (reports as error)

### ISSUE THREAD

**Issue by estaylorco** [canton7/Stylet#44]
Hello,

(Using VS 2017 and .Net 4.7)

I started with nothing but your Startup NuGet package (and the Stylet NuGet package, of course).  App.XAML looks like this:
```
<Application.Resources>
    <s:ApplicationLoader>
        <s:ApplicationLoader.Bootstrapper>
            <local:Bootstrapper />
        </s:ApplicationLoader.Bootstrapper>
    </s:ApplicationLoader>
</Application.Resources>
```

There is a red squiggly line under <s:ApplicationLoader>.  The complaint is that a key is necessary.  When I add one, however, the new complaint is that ApplicationLoader must be a member of a resource dictionary in order to have a  key.  When I surround the ApplicationLoader with a resource dictionary, that solves the problem: all squigglies disapper.   But no window appears when the application runs.

Also, despite the red squiggly (before surrounding with a dictionary), the application still runs.  Resharper/VS reports an actual error in the App.XAML file, which is disconcerting.

What's going on here?

Thank you.

**Comment by canton7** [comment]
Looks like Resharper is getting confused - that XAML is perfectly valid (s:ApplicationLoader is a ResourceDictionary, and it's valid to have a ResourceDictionary assigned to the Application's Resources property).

You can also try this, see if Resharper likes it:

```xaml
<Application.Resources>
    <ResourceDictionary>
        <ResourceDictionary.MergedDictionaries>
            <s:ApplicationLoader>
                <s:ApplicationLoader.Bootstrapper>
                    <local:Bootstrapper/>
                </s:ApplicationLoader.Bootstrapper>
            </s:ApplicationLoader>
        </ResourceDictionary.MergedDictionaries>
    </ResourceDictionary>
</Application.Resources>
```

**Comment by estaylorco** [comment]
That did the trick!  You know, I was close: I did manage to get to the ResourceDictionary, but I hadn't thought to go further with MergedDictionaries.  I will bring this to the attention of the Resharper team.

Thank you!
