### ISSUE TITLE
Unable to specify AutofacBootstrapper in XAML

### ISSUE THREAD

**Issue by estaylorco** [canton7/Stylet#45]
Based on your documentation and the Bootstrappers project on GitHub, I have configured the bootstrapper for Autofac (my root viewModel is ShellViewModel):

```
    public class AutofacBootstrapper<TRootViewModel> : BootstrapperBase where TRootViewModel : class
    {
        ...
    }
```

In App.xaml, I have this:

```
<Application x:Class="MyApp"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:local="clr-namespace:MyApp"
             xmlns:s="https://github.com/canton7/Stylet"
             xmlns:stylet="clr-namespace:Stylet;assembly=Stylet"
             xmlns:pages="clr-namespace:MyApp.Pages">
    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
            <s:ApplicationLoader>
                <s:ApplicationLoader.Bootstrapper>
                        <local:AutofacBootstrapper"/>
                </s:ApplicationLoader.Bootstrapper>
            </s:ApplicationLoader>
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </Application.Resources>
</Application>
```

Resharper/VS complains that `local:AutofacBootstrapper` has the incorrect number of parameters.  Apparently, the following is necessary:

```
<stylet:AutofacBootstrapper x:TypeArguments="pages.ShellViewModel"/>
```

But then, the complaint is that TypeArguments is not allowed in XAML versions below 2009. 

What am I missing?

Thank you.

**Comment by canton7** [comment]
You're supposed to make your own bootstrapper which subclasses AutofacBootstrapper, in the same way that you create your own bootstrapper which subclasses the default Bootstrapper<TRootViewModel>. I'll update the docs to be clearer if necessary when I'm at a proper computer.

**Comment by estaylorco** [comment]
Ah, I get it!  I took your documentation too literally where it suggests that I just copy the bootstrapper of choice into my project.

This did the trick:

```
public class Bootstrapper : AutofacBootstrapper<ShellViewModel>
{
    ...
}
```

But, yes, perhaps a small snippet in the documentation might help to clarify!

Thanks very much.

Cheers

**Comment by canton7** [comment]
Cool, I've updated the docs!
