### ISSUE TITLE
Binding different views to the same viewmodel

### ISSUE THREAD

**Issue by estaylorco** [canton7/Stylet#46]
I'm coming back to the desktop from Rob Eisenberg's Aurelia, which is a web port of Caliburn.Micro (but significantly evolved).

In Aurelia, exactly as with Stylet, if no view is supplied in the compositional binding, a naming convention is followed for pairing views to viewmodels.  But with Aurelia, we can do something like this (translating into Stylet's idiom):

```
<DataTemplate>
    <ContentControl s:View.Model="{Binding NavTabViewModel}" s:View="NavTabGroupView"></ContentControl>
</DataTemplate>
```

or perhaps

```
<DataTemplate>
    <ContentControl s:View.Model="{Binding NavTabViewModel, View=NavTabGroupView}"></ContentControl>
</DataTemplate>
```

Often times we wish to bind different views to the same underlying viewmodel (e.g. a calendar with Day, Week,  Work-week, and Month views).

Is this possible with Stylet?

**Comment by canton7** [comment]
It's not currently supported (although you can have multiple subclasses of one VM if you want). Although you could write your own ViewManager which does its own view lookup based on something... 

Specifying the concrete view type in the parent view somewhat goes against VM-first, as it means that the View/VM hierarchy is specified twice: once in the views, and again in the VMs.

Given however that you seem happy with naming the View explicitly in its parent View, why even use a ContentControl? Something like `<MyView DataContext="{Binding SomeVm}" s:View.ActionTarget="{Binding SomeVm}"/>` would work, although it's long-winded. I guess I could make `s:View.Model` do the same thing when it isn't used on something with content, so `<MyView s:ViewModel="{Binding SomeVm}"/>`.

**Comment by estaylorco** [comment]
Hello Antony,

You know, now that you've said what you've said, I don't think there's a need to change the framework.  Subclassing makes the most sense to me, and it has the added benefit of being extensible in the event greater specificity is needed (other than for purposes of satisfying a naming convention).

Unless you as the creator of the framework see a benefit to the latter example in your response, it seems like it won't be necessary.

Thanks for the response.
