### ISSUE TITLE
Accessing the Autofac container to resolve a named instance

### ISSUE THREAD

**Issue by estaylorco** [canton7/Stylet#47]
I guess I'm missing something with respect to your embrace of IoC.  Normally, with a framework like Stylet I would be able to gain access to the IoC container--it's usually ambient.  But it doesn't seem to be ambient in Stylet.

Most of the time, I simply inject my dependencies (property or constructor, depending), as we should.  Sometimes, however, obtaining an instance is a more dynamic affair.  Consider the following relevant bits of code (I'm using Autofac):

**Bootstrapper.cs**
```
protected override void ConfigureIoC(ContainerBuilder builder)
{
    base.ConfigureIoC(builder);
    builder.RegisterType<ContactsModuleViewModel>().Named<IScreen>("contactsModule");
}
```

**ShellViewModel.cs**
```
public class ShellViewModel : Conductor<IScreen>.Collection.OneActive {
public ShellViewModel()
{
    Tabs = new BindableCollection<NavTabViewModel>
    {
        new NavTabViewModel { Group = Directories, Name = "Contacts", GlyphResourceKey = "contactsDirectoryGlyph", ModuleKey = "contactsModule" },
        ...
    };
    ...
}

public void Navigate(object sender, SelectionChangedEventArgs e)
{
    var itemSelected = (NavTabViewModel)e.AddedItems[0];
    var moduleKey = itemSelected.ModuleKey;
    if (!string.IsNullOrEmpty(moduleKey))
    {
        this.ActiveItem = Container.ResolveNamed<IScreen>(moduleKey)   //***Doesn't work, of course***
    }
}
}
```

The last bit there, where I'm setting this.ActiveItem, is where I'm having trouble.  How do I gain access to the container?

**Comment by canton7** [comment]
Personally in those situations I inject a factory into the ViewModel - depending on requirements this can be something as simple as a `Func<Something>`, a `Func<Something, string>` if you need to use a key, a factory interface which the IoC container has constructed an implementation for, or a custom-built factory that I've registered with the IoC container. Referencing the container is definitely not *required*.

That said, you can sometimes register the IoC container with itself (StyletIoC does this, so if you inject `IContainer` it will give you the IoC container instance for you to use). Or you can create a static service locator, [like this](https://github.com/canton7/Stylet/wiki/IoC%3A-Static-Service-Locator).

**Comment by estaylorco** [comment]
Ah, yes, ``Func<Something, string>`` is what I was looking for.  I'm still learning where StyletIoC and Autofac intersect.  Also, I studied one of your samples further I now have a better sense of your take on factories.

I'll give this a go tomorrow and post back if I have any issues.

Thanks very much.

Cheers.

**Comment by estaylorco** [comment]
OK.  I worked it all out: I went with an abstract keyed factory.  Also, I abandoned Autofac and with Stylet’s built-in IoC.  Very cool stuff you’ve done with your IoC!
