### ISSUE TITLE
Question: Async Actions

### ISSUE THREAD

**Issue by ModernRonin** [canton7/Stylet#48]
Hi,

If I have, say, a button binding via Action to a method returning a Task, is there a way to keep the button disabled as long as the method does not return?
I might add that I'm terribly rusty with WPF, I've just come back after 5-6 years of doing other stuff, so maybe there is a very obvious answer to my question that I've overlooked - in that case sorry.

Thanks a lot for any pointers,
Max

PS: And please let me add that I like your renewed take on MVVM very much!

**Comment by canton7** [comment]
Yep, that's exactly how I'd do it as well.

**Comment by ModernRonin** [comment]
thxalot!
