### ISSUE TITLE
Action methods returning Task and exception handling

### ISSUE THREAD

**Issue by Tyrrrz** [canton7/Stylet#53]
Hi!

First of all, big thanks for this amazing library. I have just started using it and I really enjoy working with it, it's great!

One thing I love about Stylet is the `Command="{stylet:Action Execute}"` command binding. I also found it surprising (in a good way) that it handles `async` methods that return `Task`.

However, there is a little caveat, that is if the Task is not awaited or disposed, any exceptions it generates will be uncaught.

This leads to problems:
1. Exceptions are not caught so methods may silently fail to execute.
2. The whole application will crash after an arbitrary time when GC finalizes the task, causing an unhandled exception.

I haven't had the chance to look at the code yet, but I suppose it's impossible to await tasks in the code that handles execution of actions in Stylet.

One alternative solution would be trailing tasks with `.ContinueWith()` that will dispose the task on the Dispatcher thread, thus forcing the exception to be shown to the user and instantly close the application.

**Comment by Tyrrrz** [comment]
To reproduce, create an action method like this

```c#
public async Task ExecuteAsync()
{
     await Task.Delay(1000);
     throw new Exception("test"); // this exception is never handled or caught
     Console.WriteLine("123"); // this code is never reached
}
```

**Comment by canton7** [comment]
I think the best approach is to make your methods async void. This is what you'd have to do for event handlers, it has the behaviour you want here, and it's clear what's going on.

**Comment by canton7** [comment]
Ideally Stylet should throw if the return value of the method being called isn't void, to make it clear that this value is ignored, but that would potentially be a breaking change.

**Comment by canton7** [comment]
(Tasks with unobserved exceptions in them don't throw when they're finalised. There's an event on the TaskScheduler (I think?) which is fired when a task with an unobserved exception is finalised, but that's all. The best thing to do with a task you want to check for exceptions is to await it in an async void method).

**Comment by Tyrrrz** [comment]
I'm pretty sure stray tasks would throw `UnobservedTaskException`.

[Here's](https://blogs.msdn.microsoft.com/pfxteam/2011/09/28/task-exception-handling-in-net-4-5/) a bit more info about it.

>An “unobserved” exception is one that’s stored into the task but then never looked at in any way by the consuming code.  There are many ways of observing the exception, including Wait()’ing on the Task, accessing a Task<TResult>’s Result, looking at the Task’s Exception property, and so on.  If code never observes a Task’s exception, then when the Task goes away, the TaskScheduler.UnobservedTaskException gets raised, giving the application one more opportunity to “observe” the exception.  And if the exception still remains unobserved, the exception escalation policy is then enabled by the exception going unhandled on the finalizer thread.

**Comment by canton7** [comment]
Ah, that's right, the behaviour I described was introduced in .NET 4.5. From your link:

> To make it easier for developers to write asynchronous code based on Tasks, .NET 4.5 changes the default exception behavior for unobserved exceptions.  While unobserved exceptions will still cause the UnobservedTaskException event to be raised (not doing so would be a breaking change), the process will not crash by default.  Rather, the exception will end up getting eaten after the event is raised, regardless of whether an event handler observes the exception.

**Comment by canton7** [comment]
Regardless, I still think passing the Task back to Stylet is the wrong thing to do, and you should instead make your method async void.

**Comment by Tyrrrz** [comment]
Ok good points!

**Comment by canton7** [comment]
I decided to implement this

**Comment by Tyrrrz** [comment]
@canton7 just curious, what's the motivation for it, given the prior discussions we had?

**Comment by canton7** [comment]
It's just been sat somewhere near the back of my mind for a couple of years, getting mulled over I guess. I came back to Actions recently to do something else, and it popped up again. This time I came to a different conclusion 🤷
