### ISSUE TITLE
InverseBoolConverter

### ISSUE THREAD

**Issue by Tyrrrz** [canton7/Stylet#56]
Hi
Would it be possible to add a converter to this library that would convert to inverse value? Just like BoolToVisibility, this is one of the converters I use in every project and currently I have to write it myself.

I can make a PR myself if you're okay with adding this converter.

**Comment by canton7** [comment]
How would that differ from `BoolToVisibilityConverter.InverseInstance`?

**Comment by Tyrrrz** [comment]
This one converts bool to bool, not visibility. Useful when you have a bool property and you want to bind to reverse of that.
For example `IsEnabled="{Binding IsBusy, Converter={x:Static InverseBoolConverter.Imstance}}"`.

**Comment by canton7** [comment]
Ah, I see. I want to try and avoid adding things to Stylet unless necessary: there are loads of little things which a myriad of different people would find useful, but I don't think it's Stylet's place to provide them. The converters which are provided are all used internally by Stylet.

**Comment by Tyrrrz** [comment]
Yes I definitely agree, which is why I wouldn't have suggested it for any other converter. I have a bunch of specialized albeit generic converters, but this is one of those that I use literally everywhere.

Of course the same functionality can be achieved with the EqualityConverter, but it's not very pretty.

Plus it's worth noting that BoolToVisibility converter has its mention on the wiki https://github.com/canton7/Stylet/wiki/BoolToVisibilityConverter

**Comment by RThomasHyde** [comment]
Tyrrrz, you can just use BoolToVisibilityConverter with TrueVisibility and FalseVisibility inverted. No need for a separate converter. Unless I've missed the thrust of your suggestion…

**Comment by canton7** [comment]
@RThomasHyde See [this message above](https://github.com/canton7/Stylet/issues/56#issuecomment-446272232):

> This one converts bool to bool, not visibility. Useful when you have a bool property and you want to bind to reverse of that.
For example IsEnabled="{Binding IsBusy, Converter={x:Static InverseBoolConverter.Imstance}}".

**Comment by haven1433** [comment]
Tyrrrz I'd recommend adding the inverted value as a property in your ViewModel that you can bind to. That's the purpose of your ViewModel, after all: to provide a Model that maps to your View.

Given the age of this issue, it probably makes sense to close it, since no further action in Stylet is expected from this.
