### ISSUE TITLE
Can i pass Canvas to a ViewModel?

### ISSUE THREAD

**Issue by DTX-92** [canton7/Stylet#59]
I tried:
```
        public ShellView()
        {
            InitializeComponent();


            this.DataContext = new ShellViewModel(this.Canvas1);
        }
```
But it doesn't work.

**Comment by canton7** [comment]
Typically in MVVM you don't let your VM access UI elements directly. If you do need code which manipulates a Canvas directly, put that either in the codebehind or in an attached behavior. Put the *data* which should be drawn to the Canvas in the VM, and bind that into your view.

If you insist on accessing that Canvas directly from the VM, then either access `this.View` from your VM (you'll need to cast it to ShellViewModel), or put a Canvas property in the VM and bind to it in the View.

**Comment by DTX-92** [comment]
Thanks
So if i want to plot complex graph, should i still use code-behind for it?

And if i load data in viewmodel constructor, how should i tell view to render that data?

**Comment by DTX-92** [comment]
Thanks a lot!
