### ISSUE TITLE
Standalone IoC and standalone EventAggregator

### ISSUE THREAD

**Issue by pha3z** [canton7/Stylet#64]
I really like how Stylet's IOC container works and especially the EventAggregator...so much so that I'd like to use them or similar frameworks in console apps and class libraries.

Are the IoC container and EventAggregator designed to work only in the context of Stylet or can they be separated out?

**Comment by pha3z** [comment]
I looked at EventAggregator in Stylet's source code.  It looks like nothing else in Stylet depends on it, and it could easily be separated into its own class library.  To me, the EventAggregator looks useful as a module for all kinds of applications -- not just WPF MVVMs.  Is this correct?

**Comment by canton7** [comment]
Yes, the EventAggregator is fairly standalone. You could definitely use it elsewhere, but there are also a number of other good event aggregators which you could use I'm sure.

There's a rake task in Rakefile to extract the ioc container into a single file. If you've got ruby installed, run `rake extract-stylet-ioc`. I didn't bother creating a separate nuget package or anything, as there are a large number of other good ioc containers out there, and there's really no reason to use Stylet's above any of the other offerings, if you're not already using Stylet.

**Comment by pha3z** [comment]
I'm only familiar with SWAN MessageHub as another event aggregator. I think Stylet is better because:

- IHandle<eventType> implementation pattern at the start of class immediately expresses event dependencies for the class without looking at the body code. Do you know of another aggregator library that follows this approach?
- Channels, not necessary but definitely a handy bonus feature.

Regarding IoC, to the best of your knowledge, what generic IoC container is most similar to Stylet's approach?

**Comment by pha3z** [comment]
On my local build, I pulled the EventAggregator.cs into its own Project called Stylet.Events using namespace Stylet.Events.  The only piece that was dependent on Stylet itself was an EventAggregator extension method called PublishOnUiThread (because it contains a reference to Execute.OnUIThread).  I moved this particular method into its own extension class called EventAggregatorExtensions.cs as a class file in Stylet.  Basically this is the resulting heirarchy:

Stylet (includes a reference to Stylet.Events.dll)
- EventAggregatorExtensions.cs  (contains PublishOnUIThread())

Stylet.Events
- EventAggregator.cs

The build worked perfectly.  All the unit tests pass.  I included stylet.dll and stylet.events.dll in my own project, and everything works like gravy. :)  This is awesome because it let me utilize the events system in logic that is not WPF-dependent.

How do you feel about this architecture? Would you mind if I did a pull request on Stylet and made these changes in a branch that we could merge with your approval?

**Comment by canton7** [comment]
You're welcome to grab whatever files you want and incorporate them into your project - the MIT license lets you do that.

I'm not going to split Stylet up into multiple libraries however.

**Comment by pha3z** [comment]
Alright, well I think you're very smart and your framework is really good!  I feel like I've got a lot to learn, so just for my own edification, is there a general programming architecture reason for keeping them together or is it more of a matter of personal taste?

**Comment by canton7** [comment]
It's an unnecessary burden on users of the library. I would have to publish 2 NuGet packages. Every single user would have to also install the Stylet.Events NuGet package, just to support a single person who could simply copy-paste 1 file.

**Comment by pha3z** [comment]
Ok, I didn't realize that was much of a headache.  I've been using tons of NuGet packages that have separate dependency components that install automatically when you grab the package you want. I've never published a NuGet package, but their availability with automatic dependency installation in Visual Studio just makes them seem so easy.  I could see how its probably more complex than it sounds though.

**Comment by canton7** [comment]
I'm betting those of those packages have more than a single file in, though.
