### ISSUE TITLE
OnViewLoaded not documented clearly

### ISSUE THREAD

**Issue by pha3z** [canton7/Stylet#65]
The Screens and Conductors page lists OnActivate() and OnViewLoaded().  All it says about OnViewLoaded is that it occurs after the view is loaded.

If I wanted to implement logic that will change information in the view before the view is shown to the user, would I put that in OnActivate() or OnViewLoaded()?  Or is it even possible? Does the view appear before I can interact with it?

Do you have a general guideline of when to use each event?

Based on your answer here, I would be happy to edit the wiki page regarding this as a way to contribute.

**Comment by canton7** [comment]
1. If the View had already loaded at the point that it's bound to the VM, `OnViewLoaded` is called straight away. This might be just after construction, but before activation.
2. If the View hadn't loaded at the point that it's bound to the VM, `OnViewLoaded` is called when the view is loaded.

See [FrameworkElement.IsLoaded](https://docs.microsoft.com/en-us/dotnet/api/system.windows.frameworkelement.isloaded?view=netframework-4.7.2#System_Windows_FrameworkElement_IsLoaded) and [FrameworkElement.Loaded](https://docs.microsoft.com/en-us/dotnet/api/system.windows.frameworkelement.loadedevent?view=netframework-4.7.2). Basically it's highly asynchronous, and has no relation to the activation/deactivation cycle.

**Comment by pha3z** [comment]
Ok, I get it.  So I should be not thinking about sequence, but "purpose".

OnViewLoaded would be used if you needed to do any setup logic the first time the view was created. This would be useful if you need to reference the view itself for some reason.
OnActivated would be used for anything you want to happen every time a ViewModel gets activated (such as by a Conductor)

Also, anything that you can do in OnInitialActivate could be done in OnViewLoaded instead and achieve the same purpose.

Is this correct?

**Comment by canton7** [comment]
Yes, `.View` and `OnViewLoaded` are used for interacting directly with the view. The Activate/etc stuff has to do with the ViewModel lifecycle, as dictated by its parent ViewModel. The two are entirely independent.

There might not even *be* a view -- think of a parent ViewModel, which has a list of child ViewModels, and the parent View uses an ItemsControl with a DataTemplate to render each child. The ViewModel lifecycle stuff can still work (see `ConductWith`), but there won't be a view, and `OnViewLoaded` won't be called.

**Comment by pha3z** [comment]
Thanks, Antony!
