### ISSUE TITLE
Classes ending in View and ViewModel are Automatically Bound in IoC container?

### ISSUE THREAD

**Issue by pha3z** [canton7/Stylet#66]
From my understanding of the IoC container, if you use Bootstrapper<ShellViewModel>, then any classes in the project that end with View or ViewModel are automatically bound.  But any other classes I create have to be manually bound with builder.Bind<Type>() in BootStrapper ConfigureIoC() method.

Is this correct?  If yes, I'd like to add an explicit statement to the wiki explaining that. I was able to infer it by all the examples, but having it overtly stated would be helpful.

Alternatively, if I were to use BootStrapperBase<ShellViewModel>, I'd be forced to bind every single class  (even View and ViewModel classes) explicitly, correct?

**Comment by canton7** [comment]
No. All concrete types are automatically self-bound as transient instances. If there's no binding for a Foo, and you ask the container for a Foo, it will try and construct you a new instance.

See https://github.com/canton7/Stylet/wiki/StyletIoC-Configuration#autobinding

**Comment by pha3z** [comment]
I'm confused.  In the doc there it says "StyletIoC is _capable_ of creating bindings automatically for you."

It only says "capable" but doesn't indicate that it does that out of the box. And then it shows calling builder.Autobind() to bind concrete types.

Are you saying this already happens if you don't call builder.Autobind()?

Also, if all concrete types are being automatically bound as transients, what is the correct way to bind one as a Singleton to make sure that autobinding doesn't cause me to inadvertently end up with a transient for the type in question?

**Comment by pha3z** [comment]
I assume you're linking me to that to see that the DefaultCongureIoC method calls builder.AutoBind() as its last step.

What about my last question?  If I bind classes in SingletonScope() in the Bootstrapper ConfigureIoC() method, will these bindings override the transient bindings from the default IoC configuration?

**Comment by canton7** [comment]
>I assume you're linking me to that to see that the DefaultCongureIoC method calls builder.AutoBind() as its last step.

Yes. StyletIoC is capable of auto-binding types, and the base Bootstrapper for Stylet uses this functionality.

Calling `.Autobind()` just sets a flag saying "if someone requests a concrete type, and you don't have a registration for it, then try and construct it as a transient instance". I admit the wiki is a bit misleading here - I'll update it.

Consequently if you have created a binding for a type, then request it, autobinding has no impact on what you get back.

**Comment by pha3z** [comment]
> Calling .Autobind() just sets a flag saying "if someone requests a concrete type, and you don't have a registration for it, then try and construct it as a transient instance". Consequently if you have created a binding for a type, then request it, autobinding has no impact on what you get back.

The above sentences clarify a lot!  Thank you.

**Comment by canton7** [comment]
It didn't always do this, which is why the Wiki says something slightly different: it used to create explicit self bindings. However it did this after processing all other bindings, so it never clashed with bindings that the user added.

**Comment by pha3z** [comment]
>  I admit the wiki is a bit misleading here - I'll update it.

I know you're very busy. I'd be more than happy to update the Wiki regarding this issue. Would you like me to do that?

**Comment by canton7** [comment]
I did it when I posted my previous comment.

**Comment by pha3z** [comment]
Ah! Indeed!

I added the following to the IoC configuration page, continuing from your changes:

```
The Stylet bootstrapper calls Autobind(), which means Autobinding is enabled by default.

If you bind a class in Singleton scope, your specified Singleton behavior will override the Autobind transient behavior. This means you can assume all classes in Autobinded assemblies will be registered as transients, unless you explicitly register them as Singletons.
```
