### ISSUE TITLE
Suggestion:  Allow "VM" as a suffix naming convention in addition to "ViewModel"

### ISSUE THREAD

**Issue by pha3z** [canton7/Stylet#67]
Like the title says.  It would be nice if you could have this pattern:
SomeClassVM (instead of SomeClassViewModel)
SomeClassView (remains the same)

In a complex application the class names can get pretty unwieldly. Things like this:
MySpecializedWidgetMapViewModel  

Would help a lot to chop down that ViewModel part and make the code more readable.

**Comment by canton7** [comment]
You can do this by changing the relevant properties on the ViewManager. Please read the docs for that class, which explains it iirc

**Comment by pha3z** [comment]
Wow.  It seems you've thought of everything!
