### ISSUE TITLE
Assigning custom ViewModelNameSuffix Causes View Resolution To Fail

### ISSUE THREAD

**Issue by pha3z** [canton7/Stylet#71]
I tested this in Stylet.Samples.MasterDetail

I added the following code to Bootstrapper:

```
protected override void Configure()
{
    var vm = this.Container.Get<ViewManager>();

    vm.ViewModelNameSuffix = "VM";
}
```
I changed ShellViewModel to "ShellVM".

At runtime, it errors saying:

`Unable to transform ViewModel name Stylet.Samples.MasterDetail.ShellVM into a suitable View name`

**Comment by canton7** [comment]
It turns out that the ViewManager isn't registered as a singleton. I'll fix that.

As a workaround, put this in your ConfigureIoC:

```csharp
builder.Bind<IViewManager>().And<ViewManager>().To<ViewManager>().InSingletonScope();
```

**Comment by pha3z** [comment]
That works. Thanks.
