### ISSUE TITLE
No registrations found for service XXX

### ISSUE THREAD

**Issue by logwee** [canton7/Stylet#72]
I have 2 projects in my solution，one is startup project，the other is wpf lib.
I create SomeView and SomeViewModel in the wpf lib , and then use windowManager to show SomeViewModel. But I got error:
No registrations found for service SomeView

I don't know why.
Thanks

**Comment by logwee** [comment]
ShellView is in the startup project，And I use windowManager to show In the  startup project

**Comment by wakuflair** [comment]
May be the document of the [ViewManager](https://github.com/canton7/Stylet/wiki/The-ViewManager#configuring-the-viewmanager) may be helpful.

**Comment by logwee** [comment]
> You should set the `ViewAssemblies` of the ViewManager.
> The document of the [ViewManager](https://github.com/canton7/Stylet/wiki/The-ViewManager#configuring-the-viewmanager) may be helpful.

Thank you!

**Comment by slater1** [comment]
Note that I tried to do this in `Configure(...)` rather than in `ConfigureIoC(...)`. It should be done in `ConfigureIoC(...)`. See https://github.com/canton7/Stylet/issues/87
