### ISSUE TITLE
Update to new csproj and target .NET Standard

### ISSUE THREAD

**Issue by Tyrrrz** [canton7/Stylet#73]
I have the following project structure
- Core library (net46, netstd2.0)
- WPF GUI (net46)
- CLI (netcore2.1)

CLI uses Stylet only for its IoC container, in order to resolve the dependency graph in the Core library. Because Stylet only targets normal .NET Framework, this introduces issues.

With .NET Core 3.0 and new WPF just around the corner, it would also be nice to have moving forward.

**Comment by canton7** [comment]
I'm afraid I'm not entirely clear on what the problem you're trying to solve is. What are the "issues" that are introduced by Stylet targeting .NET Framework?

**Comment by canton7** [comment]
Oh, just noticed the title: you want to target .NET Standard.

Impossible I'm afraid. Stylet needs WPF - it's a framework for WPF. WPF is currently only available on .NET Framework. Therefore Stylet targets .NET Framework. If I try and target anything else, Stylet will not compile, for hopefully very obvious reasons.

When WPF for .NET Core becomes available, then Stylet will hopefully target that as well. That will probably mea .NET Core + whatever Windows-specific thing WPF gets published as. I can't do that before WPF for .NET Core is released, as there's nothing to target until then!

**Comment by Tyrrrz** [comment]
That makes sense. In that case this issue will serve as a reminder to do that as soon as possible. :)

**Comment by canton7** [comment]
I'll remember :)

**Comment by canton7** [comment]
(Also, you can't target framework and use the new SDK-style csproj at the same time)
