### ISSUE TITLE
Is there any plan to support ".net Core 3.0"?

### ISSUE THREAD

**Issue by 253513374** [canton7/Stylet#77]
Is there any plan to support ".net Core 3.0"?

**Comment by canton7** [comment]
There are plans. How soon they'll happen is another question - I'll try and take a look over the next couple of weeks.

**Comment by wakuflair** [comment]
So any progress about this? :)

**Comment by canton7** [comment]
I got Stylet built for and working on .NET Core 3, but didn't get as far as getting the unit tests working and fixing up the build/package process before my work and personal lives got very busy (see https://github.com/canton7/Stylet/compare/master...feature/netcore). I'll try and make time to finish it off soon.

**Comment by canton7** [comment]
Right, we've got .NET Core support in develop 🎉 

Mind giving it a test? Use the nuget feed https://ci.appveyor.com/nuget/stylet, and version 1.2.0.176 onwards.

**Comment by wakuflair** [comment]
Good job!
But only `Stylet` package founded, how about Stylet.Start?

**Comment by canton7** [comment]
Stylet.Start won't work with Core. I've been putting together a template for use with `dotnet new`.

**Comment by Tyrrrz** [comment]
Any chance you can push a pre-release to nuget.org?

**Comment by canton7** [comment]
It's pretty much ready to go - I'm planning to release tomorrow if I can

**Comment by Tyrrrz** [comment]
Awesome, looking forward to it.

**Comment by canton7** [comment]
It's out!

**Comment by Christian-Nunnally** [comment]
I just wanted to leave a comment here saying that I've just ported my WPF application using Stylet to .NET Core and everything seems to be working well. Thank you for all of your hard work @canton7
