### ISSUE TITLE
Configre the default namespace generated by "dotnet new stylet" CLI command.

### ISSUE THREAD

**Issue by wakuflair** [canton7/Stylet#79]
I created a project with the CLI command `dotnet new stylet`, and the default namespace generated is "Company.WpfApplication1".
Is there somewhere I can configure it? I prefer it to be the same with the project name.

**Comment by canton7** [comment]
`dotnet new stylet ProjectName`

**Comment by canton7** [comment]
`dotnet new stylet -o MyStyletProject`, as the README says.

**Comment by wakuflair** [comment]
That's exactly what I did, the default namespace still is "Company.WpfApplication1".

**Comment by wakuflair** [comment]
![image](https://user-images.githubusercontent.com/3471718/66696860-3b2c7e80-ed02-11e9-8fb8-a37ac7dd9254.png)

**Comment by canton7** [comment]
Interesting. It should have out all of the files in another namespace. I'm busy this weekend, will have a look next week.

**Comment by wakuflair** [comment]
Any news?

**Comment by canton7** [comment]
My bad, this slipped off my radar sorry!

This was a typo in the template: it'll be fixed in the next release

**Comment by jsimunac** [comment]
I just wondered if this had been fixed yet.  I just used dotnet new to create a new .NET 5 project and the default namespace is still Company.WpfApplication1.  Thanks!

**Comment by canton7** [comment]
Looks like I made the fix but haven't released it. I want to get a few things fixed for .NET 5 this weekend, so hopefully I can get a release out then.

**Comment by jsimunac** [comment]
Thank you!

**Comment by canton7** [comment]
Fixed in 1.3.5
