### ISSUE TITLE
How to use stylet in the class library project

### ISSUE THREAD

**Issue by vicwjb** [canton7/Stylet#80]
I created a new class library project with net4.5 and later, and then installed stylet.start with nuget, but did not automatically add the pages directory and Bootstrapper file to the project, so I can't run it.  So I wish you can help me.

**Comment by canton7** [comment]
Follow these instructions: https://github.com/canton7/Stylet/wiki/Quick-Start#manual-option

**Comment by vicwjb** [comment]
Yes, I have read the documentation and done it, but it didn't work. Because there is no app.xaml file in the class library.

**Comment by canton7** [comment]
You can out the bootstrapped in the class library, hit the app.xaml will need to be on the main application.

**Comment by vicwjb** [comment]
So, I want to know how to run stylet without app.xaml? Because the class library project does not require app.xaml.

**Comment by canton7** [comment]
Think about a class library which is used by a console application. You can put classes in the class library, but your Main method - the application entry point - has to be in the application. You can't have a Main method in a class library, that wouldn't make sense.

It's the same for WPF, but App.xaml is the Main method. You can put views and ViewModels and other things in the class library, but your application entry point - app.xaml - has to be in the main application.

**Comment by vicwjb** [comment]
Usually we use the class library, just need new shellview(). So, it is not called in the main method. At the same time, my requirement is to use stylet without the application entry point. I have simply implemented the ICommand and INotifyPropertyChanged interfaces and can run nicely in the class library without the application entry point. But this is not as simple and effective as stylet usage, so I still hope to use stylet in the class library.

**Comment by canton7** [comment]
I'm not sure what else to say. You cannot have your application entry point in a class library. That is fundamental and obvious. You can put everything else in a class library, but you will need some code in your main application which kicks off the bootstrapper. That can be app.xaml or it can be something else, it doesn't matter.

Just as you cannot have Main in a class library, you cannot have app.xaml in a class library. Nothing to do with Stylet.

**Comment by canton7** [comment]
Just as you do `new ShellView()` without Stylet, you can do `new Bootstrapper()` (and then call `Setup`) with Stylet, no difference. None of that means you need to try and do the impossible and put your application entry point in a class library.

**Comment by vicwjb** [comment]
I understand, i have successfully run stylet in the class library, thank you.
