### ISSUE TITLE
Cache PropertyChangedEventArgs to avoid allocations in an application with fast-changing properties

### ISSUE THREAD

**Issue by Tyrrrz** [canton7/Stylet#83]
Hey there.

I think it would be nice if we can cache `PropertyChangedEventArgs` objects per property name to avoid allocating them every time. I have some properties that change every 30ms so additional allocations induce latency.

The way I see it, the following code block needs to be slightly changed so that event args are either created or retrieved from a dictionary.

https://github.com/canton7/Stylet/blob/4fa7b9ca1a45e8d7455b101d7fed5cdc2990d069/Stylet/PropertyChangedBase.cs#L63-L75

If this enhancement is ok with you @canton7, I can make a PR.

**Comment by canton7** [comment]
I'd argue that if you're trying to do things every 30ms, MVVM (and probably even WPF) is the wrong tool to be using! If you're trying to animate things, use the built-in animations (where possible; if it's something can't use the built-in animations for, animate at the lowest level you can - definitely don't try and go through the WPF binding system). If you're trying to update changing text every 30ms, don't do that - it's unreadable.

All of that aside, remember that WPF lets you raise PropertyChanged events from any thread (it's a bad idea, but it works). Therefore any caching here will need to be thread-safe. That adds cost to everyone.

Therefore I'm reluctant to put this into Stylet. It's easy enough for you to subclass `Screen` and override `OnPropertyChanged` yourself, adding whatever caching is most suitable for you.

However, you'll be able to do even faster if you do something like:

```cs
public class MyViewModel : Screen
{
    private static readonly PropertyChangedEventArgs valueChangedEventArgs = new PropertyChangedEventArgs(nameof(Value));

    private int _value;
    public int Value
    {
        get => _value;
        set
        {
            if (value != _value)
            {
                _value = value;
                PropertyChanged?.Invoke(this, valueChangedEventArgs):
            }
        }
    }
}
```

**Comment by Tyrrrz** [comment]
>I'd argue that if you're trying to do things every 30ms, MVVM (and probably even WPF) is the wrong tool to be using! If you're trying to animate things, use the built-in animations (where possible; if it's something can't use the built-in animations for, animate at the lowest level you can - definitely don't try and go through the WPF binding system). If you're trying to update changing text every 30ms, don't do that - it's unreadable.

This isn't an animation, think more of an app that monitors certain changes and displays various related things.

>All of that aside, remember that WPF lets you raise PropertyChanged events from any thread (it's a bad idea, but it works). Therefore any caching here will need to be thread-safe. That adds cost to everyone.

Good point, but I think the cost should be minimal. It can be as simple as

```c#
var args = _dic.GetOrDefault(propertyName) ?? new PropertyChangedEventArgs(propertyName);
```

Standard dictionary is thread-safe on reads and it's fine if we encounter a race condition and new up an extra event args.

>Therefore I'm reluctant to put this into Stylet. It's easy enough for you to subclass Screen and override OnPropertyChanged yourself, adding whatever caching is most suitable for you.

True. But of course my first thought was to contribute back because: 1) I won't have to maintain an override of `Screen`; 2) others can benefit from it.
But at the end of the day it's up to you.

**Comment by canton7** [comment]
> This isn't an animation, think more of an app that monitors certain changes and displays various related things.

In that case it's very unlikely that you *need* to show updates every 30ms. That's going to add a ton of CPU usage that nobody needs. Throttle it back a bit, and you'll reduce CPU usage without having a noticeable difference.

> Standard dictionary is thread-safe on reads and it's fine if we encounter a race condition and new up an extra event args.

Sure, but that's the point of a cache you can't add to? You're suggesting having a dictionary which is always empty, but what's the point of that? A dictionary is *not* thread-safe if one thread is adding while another thread is reading.

> True. But of course my first thought was to contribute back because: 1) I won't have to maintain an override of Screen;

Sure, but you're asking me to maintain it, when you'll be the solve user ;)

**Comment by Tyrrrz** [comment]
Fair enough, I guess I'll add it in my own code.
