### ISSUE TITLE
How to change screens in a window by Stylet?

### ISSUE THREAD

**Issue by Ying-364** [canton7/Stylet#84]

**Comment by canton7** [comment]
I think you forgot to add a description. Can you add more details please, it's not clear what you're asking.

**Comment by Ying-364** [comment]
Forgive me for my poor English. E.g, sometimes I need to switch the user interface or user controls in the same window, but I don't want to open a new window. At present, I use the visibility property to do this，and then the ViewModel becomes very large. So is there any other way? And Can I bind UserControl to ViewModel?

**Comment by canton7** [comment]
Create [a conductor](https://github.com/canton7/Stylet/wiki/Screens-and-Conductors). This conductor is the root ViewModel for your window. Then display other screens using this conductor.

**Comment by Ying-364** [comment]
Thanks,I see.
