### ISSUE TITLE
I want to make a plug-in framework, but I don't intend to use MEF. Can I use style to implement it directly?

### ISSUE THREAD

**Issue by hilana** [canton7/Stylet#85]
For example, using AddModules, how to directly obtain all the independent class library projects that inherit StyletIoCModule through style? Or are there any good examples?

**Comment by canton7** [comment]
You can use Stylet, although you'll also need to use plenty of reflection. Other more complex IoC frameworks have some more built-in tools to help you.

You'll have to use reflection to list/load all of your assemblies, then use `Assembly.GetTypes()` to get all of the types, and find the ones which inherit from `StyletIoCModule`. Then use `Activator.CreateInstance` to instantiate them.

**Comment by hilana** [comment]
OK, I see. Thank you very much~

**Comment by nathan-alden-hp** [comment]
I'm doing this right now, for what it's worth, and seems to work okay. I did run into a problem #109 in a certain scenario, though. You might want to take a look at my bootstrapper to see how I handle this.
