### ISSUE TITLE
Question about binding properties in classes

### ISSUE THREAD

**Issue by gyuezhang** [canton7/Stylet#86]
I am new here and I have got a problem.
For example,My textblock's attribute text is bound to attribute username from class userinfo. 
When the value of username changes, the text does not change, only when the entire class is assigned a value.
Is there any way to change the text when the username changes?

**Comment by canton7** [comment]
You need to implement `INotifyPropertyChanged` in your `userinfo` class. An easy way to do this is by inheriting from `PropertyChangedBase`, [see the wiki](https://github.com/canton7/Stylet/wiki/PropertyChangedBase).

**Comment by gyuezhang** [comment]
This really helped me,thank you.
