### ISSUE TITLE
Does the view class and the viewmodel class need to be under the same folder?

### ISSUE THREAD

**Issue by gyuezhang** [canton7/Stylet#88]
Hi,there!
When I was sorting the project directory structure, I found that when the View class and the ViewModel class are not in the same directory, I will get an running error as follows:
`Stylet.StyletViewLocationException:“Unable to find a View with type GRCLNT.View.ShellView” `
I have checked my namespace and it should be fine,I want to know if these two classes must be placed under the same path.
Thx.

**Comment by canton7** [comment]
The ViewLocator takes the full namespace into account, so it replaces `ViewModel` with `View` in both the class name and the namespace.

You can configure this, see various sections in [this wiki page](https://github.com/canton7/Stylet/wiki/The-ViewManager).

**Comment by gyuezhang** [comment]
thx for help. ;)
