### ISSUE TITLE
Dispose of ViewModel does not work properly

### ISSUE THREAD

**Issue by zxgamekingdom** [canton7/Stylet#94]
If I use ```Bootstrapper : Bootstrapper<MainViewModel>```, when I close window, only ```Dispose``` of ```MainViewModel``` is called, and ```Dispose``` of ```TestViewModel``` is not called.

If I use ```Bootstrapper : Bootstrapper<TestViewModel>```, when I close window, only ```Dispose``` of ```TestViewModel``` is called, and ```Dispose``` of ```MainViewModel``` is not called.

Demo Code : https://github.com/zxgamekingdom/StyletDemo
.NetCore 3.1
Visual Studio 2019 16.4.2

**Comment by canton7** [comment]
Sorry, I'm afraid this slipped under the radar. Do you still have a repro? How is `TestViewModel` created in your first example?

**Comment by zxgamekingdom** [comment]
If I had a root window, root window use `IWindowManager.ShowWindow()` open a new window, then , the new window use `IWindowManager.ShowWindow()` open another new window, when I close all window, all the `Dispose` methods of ViewModels will be called, right? but only the `Dispose` method of view model of root window is called.
I restored the URL.
e.g.
In my demo, root window is  `TestView`, root view model is `TestViewModel`, then click open button to open a new window, the new window is `MainView`, then click open button of `MainView` to open a new `TestView`.Close all window, only the `Dispose` method of the first ViewModel is called, other ViewModels's `Dispose` not called.

**Comment by canton7** [comment]
> All the Dispose methods of ViewModels will be called, right?

No. The bootstrapper will dispose the root ViewModel on shutdown, but it's up to that ViewModel to dispose any children it has. If the root ViewModel is a `Conductor` which has one or more children that Stylet knows about, then they will be disposed by that ViewModel.

Likewise the ioc container will dispose any singleton objects, but it won't dispose any transient instances.

If you think about it, there's no alternative. Stylet simply doesn't know about ViewModels which you've created. While WPF records which windows are open, there's no sure way of getting the ViewModel for each. In addition, most windows are opened transiently, not for the whole lifetime of the application, so their parent needs to know how to dispose them (if necessary) *anyway*. There's no point in Stylet trying to jump in specifically on shutdown, when the user should be handling all cases where the child window is closed anyway.

**Comment by zxgamekingdom** [comment]
You're right. Sometimes, close a window does not mean that its ViewModel also needs to be dispose. But I think you should indicate it in the document, otherwise many people will have the same misunderstanding as me.
Thank you!

**Comment by canton7** [comment]
The wiki can be edited by anyone -- if you can identify the place you would like to some clarification, I'm happy to add some.
