### ISSUE TITLE
Starter nuget package appears to do nothing when installing it into new WPF app targeting .NET Core 3

### ISSUE THREAD

**Issue by mamift** [canton7/Stylet#95]
Hi,

The starter nuget (https://www.nuget.org/packages/Stylet.Start/) appears to do nothing when installing it into new WPF app targeting .NET Core 3.

It does work when installing it into a .NET Framework WPF app however, but when the project targets .NET Core it seems to silently fail. 

I've been getting around this by creating .NET Framework apps, installing the starter nuget and then porting it over to .NET Core.

**Comment by canton7** [comment]
That is the expected behaviour. As stated in the README, wiki and the package description, it only works for Framework.

Use Stylet.Templates for Core, see the README.

**Comment by mamift** [comment]
Oh my mistake.
