### ISSUE TITLE
How do I trigger an object's PropetyChanged events by modifying its properties?

### ISSUE THREAD

**Issue by seabluescn** [canton7/Stylet#99]
I have a problem, I have a simple requirement to control whether a text box is available by clicking a button, the code is as follows:
interface:
```xml
    <Canvas>
        <TextBox Text = "" IsEnabled = "{Binding IsTxtEnabled}"> </ TextBox>
        <Button Content = "Add" Command = "{s: Action Add}" />
    </ Canvas>
```

ViewModal:
```cs
 public class ShellViewModel: Screen
    {
        public AppStatus Status {get; set;} = new AppStatus ();
        public bool IsTxtEnabled
        {
            get
            {
                return Status.IsGood;
            }
        }
        public void Add ()
        {
            Status.IsGood =! Status.IsGood;
        }
    }
    public class AppStatus
    {
        public bool IsGood {get; set;}
    }
```

In fact, the above code does not work properly for obvious reasons. We changed the value of Status.IsGood, but did not changed the value of Status, so PropetyChanged event wasn't generated, so the interface will not change. If I modify the code as follows:
`<TextBox Text = "" IsEnabled = "{Binding Status.IsGood}"> </ TextBox>`
Or modify Status.IsGood =! Status.IsGood; to: Status = new AppStatus {IsGood =! Status.IsGood};
The program works.
The problem is: I expect that the textbox control must be binding to the IsTxtEnabled property. In order to modify the Status, a new object must be created and re-assigned. It always feels a little unpleasant. Is there a better solution?

**Comment by canton7** [comment]
You have two options.

If you want the UI to detect when `Status.IsGood` changes, then you will need to implement `INotifyPropertyChanged` in your `AppStatus` class. Something like:

```cs
public class AppStatus : PropertyChangedBase
{
    private bool _isGood;
    public bool IsGood
    {
        get => _isGood;
        set => SetAndNotify(ref _isGood, value);
    }
}
```

Then you can either bind your `TextBox`'s `IsEnabled` property directly to `Status.IsGood`, or you can continue to bind it to `IsTxtEnabled`, but you'll need to make sure to raise a PropertyChanged notification for IsTxtEnabled whenever `AppStatus.Good` changes.

```cs
public class ShellViewModel: Screen
{
    public AppStatus Status { get; } = new AppStatus ();
    public bool IsTxtEnabled => Status.IsGood;

    public ShellViewModel()
    {
        // Raise a PropertyChanged notification for IsTxtEnabled whenever Status.IsGood changes
        Status.Bind(s => s.IsGood, (o, e) => NotifyOfPropertyChange(nameof(IsTxtEnabled)));
    }

    public void Add ()
    {
        Status.IsGood =! Status.IsGood;
    }
}
```

---------

Alternatively, you can manually raise a PropertyChanged notification for IsTxtEnabled from your Add method:

```cs
public class AppStatus
{
    public bool IsGood { get; set; }
}

public class ShellViewModel: Screen
{
    public AppStatus Status { get; } = new AppStatus ();
    public bool IsTxtEnabled => Status.IsGood;

    public void Add ()
    {
        Status.IsGood =! Status.IsGood;
        NotifyOfPropertyChange(nameof(IsTxtEnabled));
    }
}
```

**Comment by seabluescn** [comment]
The problem has been solved, thank you very much!
